import 'package:flutter/material.dart';
import 'package:fluttter_quiz_app/widgets/sizedbox.dart';
import 'package:fluttter_quiz_app/widgets/text.dart';

class MoiQuanHe extends StatelessWidget {
  MoiQuanHe({ Key? key, required this.result }) : super(key: key);
  final String result;

  final moiquanhe = [
    {
      'tinhcach':'ENFJ',
      'mqh1':'ENFJ được bạn bè đánh giá là ấm áp và tốt bụng. Những người mang tính cách ENFJ rất thích làm quen và kết bạn với mọi người. ENFJ dễ dàng giao tiếp với mọi người, kể cả với những người kín đáo. Điều đáng nói là các ENFJ khá chọn lọc khi nói đến việc tìm những người bạn thân thiết nhất - họ đánh giá cao tính trung thực và sự chân thành, và họ không cởi mở với tất cả những người mà họ quen biết.',
      'mqh2':'Mặt dù thuộc nhóm Tình cảm ( F ), nhưng các ENFJ cũng đưa ra những lời chỉ trích khi cần thiết. ENFJ không thích điều này, nhưng họ cũng khá kiên quyết và chỉ trích nếu tình hình đòi hỏi. Nói chung, mặc dù, ENFJ có xu hướng rất khéo xử và tốt bụng, thậm chí đến mức quá ngọt ngào. Thật khó mà cưỡng lại việc kết bạn với ENFJ - đôi khi họ có thể là hơi cứng nhắc, nhưng nghị lực và sự chân thành của họ sẽ xoa dịu mọi thứ.',
      'mqh3':'Các ENFJ khá lý tưởng hóa khi tìm kiếm bạn thân, họ muốn tìm được những người bạn tốt nhất như họ tưởng tượng. Một cách tiếp cận như vậy chắc chắn là đáng khen ngợi, nhưng những người mang loại tính cách ENFJ cần phải chắc chắn rằng sự nhiệt tình của họ không làm "ngột ngạt" người khác. ENFJ là những người bạn luôn ủng hộ, vui vẻ và nồng nhiệt.',
      'mqh4':'Các ENFJ đều có khả năng và sẵn sàng làm việc vì tình bạn của họ, và đặt chúng rất cao trong danh sách công việc ưu tiên của họ. ENFJ rất vui trong việc giúp đỡ mọi người khám phá điểm mạnh và niềm đam mê của họ, và sau đó hỗ trợ mọi người để phát triển tiềm năng đó. Đây không phải là hoàn toàn vị tha bởi vì ENFJ cũng mong muốn bạn bè cũng trả ơn xứng đáng với những gì đã được ENFJ giúp đỡ - tuy nhiên, ENFJ chắc chắn sẽ được đánh giá cao và rất được tôn trọng.',
      'mqh5':'Tóm lại, các ENFJ luôn nhiệt tình và nỗ lực trong việc tìm kiếm và duy trì các mối quan hệ. Ở mức độ nào đó, ENFJ định nghĩa bản thân họ bằng sự gần gũi và trung thực trong các mối quan hệ cá nhân của mình, do đó họ đầu tư nhiều vào các mối quan hệ như thể đó là công việc của họ. ENFJ có khả năng ứng xử tốt, có sự nhiệt tình cũng như chu đáo với mọi người. Họ chấp nhận và quan tâm ân cần. Họ vượt trội trong khả năng mang đến những điều tốt đẹp cho người khác và giúp đỡ người khác một cách nồng nhiệt. Các ENFJ muốn sự xác nhận của đối phương dù gặp không ít khó khăn khi hỏi về điều đó. Khi một tình huống diễn ra, họ trở nên nhạy bén và sắc sảo. Sau khi đưa ra quan điểm của mình, họ trở về với bản chất ấm áp của mình. Họ có thể có xu hướng "yêu thương quá mức" với những người mà họ yêu quý, nhưng nhìn chung thì các ENFJ được đánh giá cao bởi sự chân thành và sự quan tâm tự nhiên của họ.'
    },
    {
      'tinhcach':'ENFP',
      'mqh1':'Các ENFP luôn là những người bạn vui vẻ, chân thành và cởi mở. Họ hiếm khi gặp khó khăn để hiểu loại tính cách khác và tương tác với chúng trong "ngôn ngữ" của họ. Đây là một đặc điểm rất hiếm và có giá trị - mặc dù một số bạn bè của ENFP có thể không thể đáp lại, họ chắc chắn sẽ nhận ra và đánh giá cao những nỗ lực của ENFP. Những người có loại cá tính này thường có khả năng thu hút ngay cả những người bạn có nhiều lớp vỏ bọc tính cách.',
      'mqh2':'Vì các ENFP rất trực quan, họ ít khi gặp khó khăn để tìm ra những gì thúc đẩy và truyền cảm hứng cho bạn bè của họ. Nhiệt tình và ấm áp các ENFP rất dễ lan truyền, vì chúng xuất phát từ chủ nghĩa lý tưởng tinh khiết. Tuy nhiên, các ENFP nên chắc chắn rằng sự theo dõi của mọi người là không nhàm chán - không phải tất cả mọi người đều có thể tiếp thu hết những luồng ý tưởng và chủ đề mà tâm trí của một ENFP có thể tạo ra.',
      'mqh3':'Những người bạn ENFP có xu hướng rất quan tâm và ủng hộ, nhưng họ cũng cần phải đảm bảo rằng nhu cầu của họ được đáp ứng. Những người có loại cá tính này thường liên quan nhiều và can thiệp sâu đến cuộc sống của bạn bè, thậm chí quên chăm sóc cho bản thân. Hơn nữa, các ENFP cũng có xu hướng nuôi dưỡng những kỳ vọng không thực tế khi nói đến tình bạn. Điều này có khả năng có thể dẫn đến căng thẳng và thất vọng khi nhận ra rằng bạn bè của họ không phải là hoàn mỹ hay tậm tâm như họ muốn.',
      'mqh4':'Nói chung, ENFP có thể sẽ là khá duy tâm và nhạy cảm. Cái gì cũng có mặt trái của nó và sự nhạy cảm của ENFP không phải là một ngoại lệ - nó cho phép họ kết nối với bạn bè và người quen rất dễ dàng, nhưng cũng làm cho ENFP rất dễ bị chỉ trích. Đây là lý do tại sao các ENFP có xu hướng tránh những người có cá tính mạnh T và J - những loại cá tính đó có thể có ý kiến ​​mạnh mẽ về một loạt các chủ đề và các ENFP có thể sẽ cảm thấy khá khó chịu tranh luận với họ.',
      'mqh5':'Tóm lại, các ENFP rất nghiêm túc trong các mối quan hệ, tuy nhiên lại tiếp cận nó với sự nhiệt tình và nỗ lực một cách hồn nhiên. ENFP đòi hỏi và yêu cầu sự chân thành, sâu sắc từ các mối quan hệ, các ENFP sẽ cố gắng hết sức để khiến mọi việc như ý muốn. ENFP rất nhiệt tình, đáng tin cậy, chu đáo và luôn cố gắng nuôi dưỡng các mối quan hệ của mình. Họ có khả năng giao tiếp rất tốt, và có khả năng truyền cảm hứng, giúp cho người khác bộc lộ hết năng lực mà họ có thể. Năng động và sôi nổi, ENFP rất hay đắm mình trong lửa đam mê cuồng nhiệt, và thường được đánh giá cao bởi sự nồng hậu chân thành và lý tưởng cao đẹp.'
    },
    {
      'tinhcach':'ENTJ',
      'mqh1':'Các ENTJ tìm kiếm hai điều chính trong tình bạn, đó là sự truyền cảm hứng và phát triển cá nhân. Không giống như nhiều nhóm tính cách khác, họ không thực sự cần hỗ trợ nhiều về tinh thần hay sự trấn an. Tuy nhiên, ENTJ thích thú các ý tưởng hấp dẫn bí ẩn, các cuộc thảo luận có ý nghĩa với những người bạn thân. Những người có loại tính cách này rất giỏi nhận ra các cơ hội học tập và phát triển - và họ luôn luôn cố gắng khuyến khích bạn bè của họ cùng tham gia.',
      'mqh2':'Nhìn chung, ENTJ dành khá nhiều thời gian để chú ý đến tình bạn. Không dễ để trở thành bạn thân của ENTJ, họ là những con người có ý chí mạnh mẽ, rất thông minh, giỏi tranh luận và chỉ trích. Không phải ai cũng có thể chịu đựng được một cuộc tranh luận với họ - và điều này là lý do chính tại sao ENTJ tôn trọng và đánh giá cao những người có khả năng bảo vệ quan điểm của mình. Điều đáng nói, ENTJ không hiểu và cũng không tôn trọng các lý do và hay thỉnh cầu mang tính tình cảm. Họ là những con người rất lý trí, chỉ có thể chấp nhận một quan điểm khác nếu nó được chứng minh bởi sự logic và hợp lý.',
      'mqh3':'Đương nhiên, ENTJ cũng gặp khó khăn khi hỗ trợ người khác về mặt tình cảm. Đối phó với cảm xúc chắc chắn không phải là điểm mạnh của họ, và họ làm mọi cách để tránh các tình huống cảm xúc. ENTJ thích thách thức bạn bè của họ, và chất vấn các kết luận của họ. Đây là loại tính cách đặc biệt dễ bị chỉ trích và có xu hướng rất cá nhân.',
      'mqh4':'ENTJ có xu hướng đặt sự trau dồi và phát triển bản thân lên trên mọi thứ khác khi nói đến tìm kiếm và xây dựng mối quan hệ cá nhân, thật đáng nghi ngờ khi họ sẽ theo đuổi các mối quan hệ mà không cung cấp những cơ hội như vậy. ENTJ bị lôi cuốn bởi các nhóm trực giác khác ( những nhóm có đặc điểm I ) vì những người này sẽ tạo cho họ cơ hội để động não và đưa ra giả thuyết về những điều mà họ cho là quan trọng.',
      'mqh5':'Tóm lại, các ENTJ luôn nhiệt tình và nỗ lực hết mình trong các mối quan hệ của mình. Phương châm của ENTJ là "Học, học nữa, học mãi" nên họ sẽ cố gắng tiếp thu và biến mọi thứ thành bài học kinh nghiệm của mình. Đối với các mối quan hệ, các ENTJ sẽ không ngừng học hỏi và xem lại các nguyên tắc và tính chất của các mối quan hệ đó. Họ vô cùng trân trọng các mối quan hệ, nhất là các mối quan hệ mang lại cho họ nhiều thử thách mới và kích thích tinh thần học hỏi. Trong quá trình tiếp thu kiến thức đó, nó đã góp phần nâng cao tình cảm đích thực và sự hài lòng cho các ENTJ. Họ không thích các mối quan hệ chẳng mang lại cho họ cơ hội để học hỏi và phát triển. Trong cuộc sống, các ENTJ muốn được là người nhận trách nhiệm trong các mối quan hệ. Trong giao tiếp hàng ngày ENTJ thường thẳng thắn nên dễ gây xung đột, đôi khi họ còn chỉ trích thậm tệ và gây khó khăn cho người khác. Người có mối quan hệ mật thiết với các ENTJ cần phải thật mạnh mẽ, đối với những người như vậy, ENTJ sẽ mang lại cho họ nhiều điều thú vị.'
    },
        {
      'tinhcach':'ENTP',
      'mqh1':'Không có người bạn nào có thể nhanh trí và lý luận như những ENTP. Các ENTP thực sự rất thích tranh luận và họ có thể bỏ cả buổi tối để bảo vệ một quan điểm, cho dù họ cũng không tin quan điểm đó là đúng. Nếu bạn bè của ENTP có thể giữ quan điểm của họ và đưa ra các giá trị, lập luận hợp lý, sau đó các ENTP sẽ cân nhắc, điều này là hình tượng tiêu biểu của một tình bạn.',
      'mqh2':'Các bạn bè của ENTP không thể thấy được sự nhạy cảm và tình cảm của ENTP, cho dù họ rất trực quan. Những người có cá tính ENTP thường biết đến như những kẻ lý trí và vô cảm - họ có thể khá vui tính và nhiệt tình, nhưng không phải là chỗ dựa tinh thần cho những người đang buồn. Họ chắc chắn sẽ đưa ra những giải pháp hoàn toàn logic và hợp lý, nhưng cảm xúc và tình cảm là điều mà ENTP muốn bác bỏ.',
      'mqh3':'Nhìn chung, các ENTP không gặp khó khăn khi giao tiếp với bạn bè và những người thuộc nhóm tính cách khác, đặc biệt là nếu họ không ngại đề nghị và thảo luận các ý tưởng và điều hấp dẫn mới (các ENTP nên chắc chắn rằng điều này không trở thành một cuộc cạnh tranh, cãi vã). Tuy nhiên, khi không cùng quan điểm với người tranh luận các ENTP ít khi danh nhiều thời gian để đặt mình vào vị trí của người đó.',
      'mqh4':'Tóm lại, ENTP là loại người tự nhiên, thoải mái và lạc quan, họ có thể làm mọi người xung quanh vui vẻ. ENTP nhận được rất nhiều niềm vui và sự hài lòng từ việc gây ảnh hưởng với những người khác, đặc biệt trong việc tranh luận về những giả thuyết và ý niệm gây cho họ sự hứng thú. Các ENTP cũng có xu hướng khởi xướng cuộc tranh luận bởi họ rất thích tranh cãi. Họ thường vui vẻ và thích giao du, cũng như rất quyến rũ. Họ gặp vấn đề mất tập trung trong công việc và đôi khi còn lơ là các mối quan hệ thân thiết khi phải tham gia vào một dự án hoặc một ý tưởng mới.',
      'mqh5':''
    },
    {
      'tinhcach':'ESFJ',
      'mqh1':'ESFJ là những người bạn rất trung thành và sẵn sàng bỏ ra rất nhiều thời gian với những người quan trọng với họ. Họ là những người nồng nhiệt, sống tập thể và rất truyền thống. Các ESFJ tìm kiếm các mối quan hệ tốt, bền vững và họ làm mọi thứ để bạn bè của họ hạnh phúc. Không ngạc nhiên, khi các ESFJ được nhiều người ngưỡng mộ và yêu thích.',
      'mqh2':'Các ESFJ thích làm cho bạn bè của họ cảm thấy thỏa mái, nhưng họ cũng mong đợi được đền đáp lại. Những người có loại cá tính này không thích chỉ trích mạnh mẽ, đặc biệt là nếu ý kiến ​​tiêu cực đến từ những người mà họ tin tưởng. Điều quan trọng là các ESFJ cũng không bị phán xét khi nói đến việc giao tiếp với những người không cùng quan điểm.',
      'mqh3':'Những người có các loại tính cách ESFJ cũng nên lưu ý rằng sự nhạy cảm của họ cho phép họ nhận ra những gì động viên và thúc đẩy bạn bè của họ - kiến thức này có thể được sử dụng cho cả hai mặt, mặt tốt (khuyến khích và truyền cảm hứng của người khác) và mặt xấu (thao túng và điều khiển). Thật không may, nhiều ESFJ quá tin tưởng vào bạn bè, rằng bạn bè của họ có thể làm không sai, luôn luôn đẩy mạnh và bảo vệ họ bất kể tình hình.',
      'mqh4':'Những người bạn ESFJ luôn cố gắng rất nhiều để giữ mối quan hệ cá nhân tốt, và các mối quan hệ xã hội tốt đẹp khác. Dễ tính và chân thành là hai tính cách giúp họ chinh phục nhiều người quen và bạn bè.',
      'mqh5':'Tóm lại, các ESFJ sống rất tình cảm và luôn đánh giá cao những mối quan hệ thân thiết cá nhân. ESFJ luôn muốn phục vụ người khác, và họ hạnh phúc khi thấy những người thân yêu bên cạnh mình sống vui vẻ. Họ được đánh giá cao bởi sự ấm áp, chân thành và bản chất quan tâm của mình, cũng như khả năng đặc biệt có thể nhận ra và phát triển những thế mạnh của người khác. Họ thường không giỏi giải quyết xung đột, nhưng thường có xu hướng rất điềm tĩnh và thuyết phục. Những mối quan hệ được đặt làm trọng tâm trong cuộc sống của họ, và họ luôn nỗ lực hết mình để phát triển và duy trì những mối quan hệ cá nhân. Các ESFJ cũng mong muốn có được điều này từ những người khác.'
    },
    {
      'tinhcach':'ESFP',
      'mqh1':'Những người mang tính cách ESFP chắc chắn sẽ có nhiều bạn bè - bởi vì gần như không thể cưỡng lại sự nhiệt tình và lạc quan của họ. Những người có loại cá tính này tập trung hoàn toàn vào hiện tại và luôn luôn tìm thấy một cái gì đó thú vị để trải nghiệm và chia sẻ với bạn bè của họ. Điều này không có nghĩa là mối quan hệ của họ là nông cạn hoặc dựa hoàn toàn vào niềm vui - hoàn toàn ngược lại. Các ESFP chân thành quan tâm đến người khác, nhưng họ chỉ đơn giản tin rằng không có mục tiêu trong cuộc sống nếu bạn không thể cảm thấy thật sự sống.',
      'mqh2':'Mặt khác, khả năng chi phối tuyệt vời tất cả năm giác quan của các ESFP, có thể đẩy họ tham gia vào hành vi nguy cơ, ví dụ như cờ bạc, trai gái, nhậu nhẹt,... Đây là lý do tại sao các ESFP nên có bạn bè với các loại tính cách khác nhau thay vì xung quanh mình với những người hành động và suy nghĩ theo cách tương tự (ví dụ như hầu hết các nhóm tính cách SP khác).',
      'mqh3':'Những người bạn ESFP không có bất cứ khó khăn giao tiếp với các loại tính cách khác. Họ rất thẳng thắn, thậm chí đôi khi lỗ mãng, nhưng sự cởi mở và quyến rũ của họ dễ dàng xoa dịu cơn giận. Những người có loại cá tính này biết làm thế nào để vui chơi và hạnh phúc hơn khi chia sẻ niềm vui đó với bạn bè của họ, miễn là họ sẵn sàng đáp lại.',
      'mqh4':'Các ESFP sẽ tránh xa các thảo luận về vấn đề trí tuệ, logic, trừ khi họ xoay quanh các vấn đề thực tế, thường nhật và thú vị. Do đó các ESFP sẽ khó liên hệ, kết giao với những nhà phân tích (NT) hay nhà ngoại giao (NF). Khi đó họ sẽ đưa ra ý tưởng hay hành động mà cả hai đều được hưởng.',
      'mqh5':'Nhìn chung, các ESFP rất vui tính và thú vị khi tiếp xúc. Họ sống với hiện tại và biết cách làm cho mỗi giây phút đó trở nên tuyệt nhất. Họ thích thú một cách chân thành và ấm áp với người khác, và yêu thích làm cho người khác hạnh phúc. ESFP thường rất tốt bụng và hào phóng và luôn hết mình làm những điều tốt cho người khác. Cách thể hiện tình cảm của họ đơn giản, thẳng thắn và chân thành. Họ không thích lý thuyết và sự phức tạp. Các ESFP thường không thích những mối quan hệ đòi hỏi họ phải sử dụng trực giác hay suy nghĩ nhiều. ESFP thích mọi thứ phải vui vẻ và đằm thắm dù cho tình cảm hay sự nồng nhiệt của họ rất sâu sắc. Khuyết điểm của các ESFP là sống hết mình cho thời điểm hiện tại, do đó đôi khi họ không nhận ra hướng đi của các mối quan hệ hoặc dễ dàng bị mất mục tiêu của mình.'
    },
    {
      'tinhcach':'ESTJ',
      'mqh1':'Các ESTJ thích kết bạn với những người có chung quan điểm tôn trọng truyền thống và các nền tảng chắc chắn. Những người có loại cá tính này tìm kiếm các mối quan hệ chặt chẽ với bạn bè của họ, nhưng ESTJ thường gặp khó khăn để chấp nhận các ý kiến quá ​​khác nhau hoặc tiếp tục kiên nhẫn làm theo ý họ trong khi vẫn lắng nghe mọi người - do đó, có khả năng là bạn bè thân thiết của họ sẽ chủ yếu bao gồm các loại SJ khác .',
      'mqh2':'Tính cách ESTJ có xu hướng trở thành những người bạn cởi mở và nhiệt tình. Họ cũng sẽ rất trung thành, mặc dù gia đình và các nguyên tắc của họ sẽ luôn luôn là ưu tiên hàng đầu. Các ESTJ cũng có khả năng chủ động hoặc thậm chí chi phối, khuyến khích bạn bè của họ tham gia vào các sự kiện khác nhau và các hoạt động xã hội. Những người có loại cá tính này thường thích thể thao và các hoạt động thể chất khác, vì vậy họ có thể sẽ khuyến khích bạn bè cùng tham gia.',
      'mqh3':'Các ESTJ cần nỗ lực có ý thức để lắng nghe lập luận của người khác và cố gắng hiểu quan điểm của họ trước khi đưa ra bất kỳ kết luận nào - những ESTJ thường có ý kiến rất mạnh mẽ khi nói đến nguyên tắc và niềm tin của họ, họ thường bướng bỉnh và cứng nhắc. Sẽ thật tốt nếu có ít nhất một vài người bạn thỉnh thoảng không đồng ý với họ - Các ESTJ nên dành thời gian với những người bạn khác, những người mà không áp dụng cách tiếp cận truyền thống của họ vào cuộc sống.',
      'mqh4':'Đặt những yếu kém trên sang một bên, những người có các loại tính cách ESTJ có thể sẽ là những người bạn năng động, đáng tin cậy và dí dỏm. Họ có thể không phải là linh hồn của tập thể, nhưng bạn sẽ không cảm thấy buồn chán khi làm việc chung với họ nếu bạn cũng có chung một số quan điểm với họ.',
      'mqh5':'Tóm lại, các ESTJ rất nhiệt huyết. Họ khát khao muốn hoàn thành trách nhiệm và nghĩa vụ của mình, đặc biệt là khi chúng liên quan tới gia đình. Ưu tiên của ESTJ thông thường theo thứ tự sau: chúa trời, gia đình và cuối cùng là bạn bè. Họ cố gắng nỗ lực hết mình để hoàn thành những công việc được giao dựa trên thứ tự ưu tiên trên. Họ rất tận tâm và luôn có trách nhiệm trong các mối quan hệ của mình mà họ cho rằng chúng sẽ kéo dài mãi mãi và không thể thay đổi được. ESTJ thích được dẫn đầu, nên trong gia đình họ rất hay kiểm soát người bạn đời và con cái của mình. ESTJ có một sự kính trọng đối với truyền thống và thể chế, họ cũng kỳ vọng rằng người bạn đời và con cái của mình cũng ủng hộ những điều này. Các ESTJ chẳng có thời gian cũng như muốn tiếp xúc với những người không cùng quan điểm với họ.'
    },
    {
      'tinhcach':'ESTP',
      'mqh1':'Các ESTP rất dễ tính và khoan dung với bạn bè, những người mà họ không bao giờ thấy nhàm chán. Trí tưởng tượng và tự phát của họ là thực sự đáng ghen tị - các ESTP luôn luôn có thể đưa ra những ý tưởng thú vị để khám phá và tìm thấy những điều thú vị để làm. Họ sống hoàn toàn trong hiện tại, ít nhìn lại quá khứ hay quan tâm đến tương lai, và điều này là một trong những lý do tại sao họ rất quyến rũ và được nhiều người ngưỡng mộ .',
      'mqh2':'Các ESTP dường như hòa thuận với mọi người và kết bạn mới ở tất cả mọi nơi họ đến. Họ trung thực, thẳng thắn và không thực sự lo lắng về cách người khác cảm nhận về họ - và điều này giúp họ thu hút bạn bè có chung quan điểm trong cuộc sống. Các ESTP thích tận hưởng thực tế và các hoạt động thể chất, vì vậy họ thường có rất nhiều cơ hội để "rèn" tình bạn mới trong môi trường mà họ cảm thấy tự nhiên. Các ESTP ít khi tìm kiếm bạn bè có tính cách thích tranh luận trí tuệ và triết học.',
      'mqh3':'Các ESTP cũng dễ bị tham gia vào các hành vi nguy hiểm và có thể khuyến khích bạn bè của họ cùng tham gia. Những người có loại cá tính này tìm kiếm sự phấn khích và chán ghét hơn bất cứ điều gì - điều này có nghĩa là họ sẽ sẵn sàng hơn để khám phá những điều mới, nhưng một đặc điểm như vậy rõ ràng cũng có nhược điểm.',
      'mqh4':'Tóm lại, các ESTP là những người rất thích giao tiếp, dễ tính và luôn mong muốn tận hưởng từng khoảnh khắc tuyệt vời của cuộc sống. ESTP thích hành động và luôn mong muốn làm việc. Cảm hứng này lan truyền đến những mối quan hệ của họ, và họ khát khao trong việc tận dụng và phát triển các mối quan hệ hàng ngày. Họ mau chán và thấy rất buồn khi phải thay đổi mối quan hệ thường xuyên trừ khi họ tìm được người thích hợp. Các ESTP sống trong hiện tại, do đó những cam kết dài hạn thường không thích hợp với họ. ESTP cực kì tận tâm, và họ muốn thực hiện những cam kết của mình hằng ngày.',
      'mqh5':''
    },
    {
      'tinhcach':'INFJ',
      'mqh1':'Những người bạn INFJ rất sâu sắc, ấm áp và chu đáo. Không dễ để tìm hiểu về INFJ vì họ thường che giấu cảm xúc sâu bên trong tâm trí họ. Loại tính cách INFJ này rất bí ẩn và khó để giải mã nhưng họ lại có thể nhìn thấu mặt nạ của người khác rất dễ dàng. Tính trung thực và chân thành là rất quan trọng nếu bạn muốn trở thành bạn bè với một INFJ.',
      'mqh2':'Các INFJ không thực sự quan tâm đến "hữu nghị" mà chủ yếu là xoay quanh thực tế, các vấn đề hàng ngày hoặc các hoạt động thể chất. Họ khá im lặng nhưng lại là nhà duy tâm cương quyết, đầy ắp những mong muốn làm cho thế giới tốt đẹp hơn. Do đó, những người mang tính cách INFJ mong muốn tìm kiếm những người bạn sẵn sàng mang chủ nghĩa lý tưởng vào cuộc sống của họ và tham gia vào sâu các cuộc thảo luận có ý nghĩa về những điều vượt ra ngoài thói quen hàng ngày.',
      'mqh3':'Những người bạn INFJ có xu hướng tương đối lý tưởng hóa - mong muốn mọi thứ thật hoàn hảo, điều này có hai mặt, có thể rất tích cực hoặc cũng có thể tiêu cực khi nói đến các mối quan hệ. Một mặt, các INFJ sẽ tìm cách nuôi dưỡng và phát triển cùng với những người bạn thân của họ, tìm kiếm kinh nghiệm sống phong phú. Mặt khác, xu hướng này luôn luôn tiếp cận với lý tưởng có thể làm suy kiệt những người có loại tính cách khác nhau, vì họ có thể không có khả năng chịu đựng và quyết tâm mà INFJ sở hữu. Do đó, INFJ có thể tiếp tục chuyển sang một người bạn khác, hy vọng rằng một trong những người tiếp theo sẽ có nhiều điểm chung với họ hơn.',
      'mqh4':'Các INFJ nên nhớ rằng, INFJ là loại tính cách rất hiếm và không được nản lòng nếu bạn bè không chia sẻ 100% các nguyên tắc hay mục tiêu với INFJ. Những người mang tính cách INFJ muốn tìm kiếm bạn bè mà họ có thể tin tưởng, cả hai đều sẵn sàng và có thể hiểu được niềm đam mê và ý tưởng của họ. Không nhiều người có thể đương đầu với chiều sâu và sự phong phú của trí tưởng tượng của INFJ, và thậm chí ít có khả năng hỗ trợ các INFJ theo cách mà họ cần. Các INFJ có xu hướng là những người bạn rất trung thành và hay giúp đỡ, và họ cũng được các nhóm tính cách khác tìm kiếm, kết bạn vì sự khôn ngoan của họ, nhưng INFJ cần phải học cách để gặp gỡ bạn bè mới đầy tiềm năng giữa đường.',
      'mqh5':'Tóm lại, INFJ là những người ấm áp và đáng tin cậy, họ cũng rất sâu sắc và khá bí ẩn. Họ thích tìm kiếm và phát triển các mối quan hệ lâu dài và có ý nghĩa. INFJ là người cầu toàn, luôn nỗ lực cho mối quan hệ tối ưu. Trong đa số trường hợp, đây là một điều tích cực, nhưng đôi khi lại có hại cho họ nếu họ biến việc rời bỏ mối quan hệ cũ để tìm kiếm các mối quan hệ mới trở thành thói quen, để luôn tìm kiếm những người bạn mới hoàn thiện hơn. Nói chung, họ là những người nồng ấm và biết quan tâm sâu sắc, INFJ đầu tư vào mối quan hệ gần gũi, và nỗ lực nhiều để làm chúng trở nên tích cực. Các INFJ được đánh giá cao bởi những người thân cận vì năng lực đặc biệt này. Họ tìm kiếm những mối quan hệ bền vững, lâu dài mặc dù không phải lúc nào họ cũng tìm thấy nó.'
    },
    {
      'tinhcach':'INFP',
      'mqh1':'Các INFP rất khó hiểu. Ngay cả người bạn thân nhất của họ thấy khó khăn để thuyết phục các INFP cởi mở và tiết lộ cảm xúc của mình - những người quen biết bình thường càng không thể hiểu chút gì về nội tâm của INFP. Những người có loại tính cách này không quan tâm nhiều về số lượng bạn bè mà họ có, họ quan tâm đến chất lượng của tình bạn hơn.',
      'mqh2':'Những người bạn INFP đặc biệt trung thành và hay giúp đỡ. Họ cũng nhận biết được trạng thái tình cảm và cảm xúc của người khác, và đặc điểm này đã làm cho các INFP trở nên rất nhạy cảm và sâu sắc. Những người có loại tính cách này rất riêng tư khi nói đến cảm xúc của mình - một lần nữa, các INFP không cảm thấy thoải mái để lộ cảm xúc của họ với những người mà họ không biết rõ.',
      'mqh3':'Các INFP thường rất giỏi trong việc thấu hiểu những động cơ của người khác và không có khó khăn lọc ra những người đáng ngờ. Tuy nhiên, nếu các INFP quyết định cởi mở và bắt đầu tin tưởng người khác, họ sẽ hình thành một mối quan hệ rất mạnh mẽ và ổn định. Cũng cần lưu ý rằng các INFP cảm thấy rất tôn trọng những người có nguyên tắc và các giá trị giống như vậy - những quan niệm này rất thân thiết với những người có loại tính cách này.',
      'mqh4':'Các INFP sẽ cảm thấy thỏa mái nhất khi kết bạn với những người mang đặc tính Feeling ( F ) - Tình cảm. Tính hợp lý và nhận thức "lạnh lùng" của đặc điểm Thinking ( T ) - Lý trí có thể được đe dọa họ, trong khi đặc điểm Judging ( J ) - Nguyên tắc có thể xuất hiện quá quyết đoán và cứng nhắc. Điều này không có nghĩa là INFP không thể giao tiếp với những người mang đặc điểm trên, chỉ có điều là họ khó có khả năng trở thành những người bạn thân.',
      'mqh5':'Tóm lại, các INFP thể hiện một phong thái rất bình tĩnh, hiền hòa đối với cuộc sống. INFP xuất hiện để mang lại sự yên tĩnh và thanh bình cho mọi người, với những ước vọng đơn giản. Trên thực tế, các INFP cảm nhận cuộc sống của mình một cách mạnh mẽ. Trong quan hệ, điều này đã khiến cho họ có đầy cảm xúc sâu lắng cho yêu thương và sự quan tâm, điều này không thường thấy ở các nhóm tính cách khác. Các INFP không dành trọn tất cả tình cảm mãnh liệt của họ cho riêng một ai và khá dè dặt trong việc bộc lộ cảm xúc sâu lắng của mình. INFP dành tình cảm và sự quan tâm sâu sắc nhất cho một vài người thân hay những người mà tin tưởng nhất. Họ nhìn chung thoải mái, thích giúp đỡ và nuôi dưỡng các mối quan hệ gần gũi. Với cảm xúc nội tâm làm chủ tính cách, các INFP rất nhạy cảm và dễ đồng cảm với cảm giác của mọi người, và cảm thấy thật sự quan tâm và lo lắng cho người khác. Không dễ tin tưởng người khác và thận trọng trong khi khởi đầu một mối quan hệ, nhưng INFP sẽ hết mực trung thành một khi họ đặt ra một lời cam kết. Với những giá trị cốt lõi mạnh mẽ, INFP là những cá nhân đánh giá cao chiều sâu và sự chân thật trong các mối quan hệ và coi trọng những người bạn có thể hiểu và chấp nhận quan điểm của INFP. Họ thường dễ hòa nhập và thông cảm, trừ khi một trong những nguyên tắc sống của họ bị xâm phạm thì khi đó họ không tiếp tục hòa nhập và trở nên bảo thủ cho những nguyên tắc của họ. Các INFP sẽ trở nên khắc nghiệt và cứng nhắc trong tình huống như vậy.'
    },
    {
      'tinhcach':'INTJ',
      'mqh1':'Không dễ dàng để trở thành bạn của INTJ. Họ đánh giá lý trí và sự thông minh cao hơn bất cứ điều gì khác, và có xu hướng tự cho rằng hầu hết mọi người họ tiếp xúc có thể kém thông minh hơn họ. Phần lớn có lẽ sẽ gọi đó là kiêu ngạo; các INTJ sẽ hợp lý hóa điều này như một cơ chế lọc tự nhiên và và tranh cãi làm cho người ta rất dễ chán nản họ. Do đó, các INTJ thường có rất ít bạn bè tốt - nhưng họ cũng không thực sự thấy cần thiết phải có một danh sách bạn bè đông đảo.',
      'mqh2':'Tính cách INTJ rất độc lập và tự lập. Họ nhìn nhận bạn bè của họ như là để trao đổi về trí tuệ và kiến thức hơn là một cầu nối để liên kết với xã hội bên ngoài. Các INTJ thấy hạnh phúc khi đưa ra những cách thức mới để cải thiện và làm sâu sắc thêm mối quan hệ, nhưng họ sẽ không phụ thuộc vào tình cảm bạn bè của họ. Hơn nữa, các INTJ sẽ không thích những biểu lộ thể chất của cảm xúc (ôm ấp vuốt ve, chạm,...), ngay cả với bạn bè thân thiết.',
      'mqh3':'Những người bạn INTJ cũng thấy rằng những người có loại cá tính này rất khó để "đọc" (khó đoán). Các INTJ không chỉ là điềm nhiên, không xúc động, mà họ cũng có khả năng để cố gắng ngăn chặn những cảm xúc thông qua các bộ lọc tinh thần của họ - do đó cảm xúc chính là điểm yếu của họ, họ làm hết sức mình để chúng không thể hiện ra bên ngoài, vì lo sợ điều này sẽ vi phạm những chuẩn mực của lý trí và tư duy logic mà họ đã đặt ra. Và ngược lại, các INTJ không nhạy cảm khi nói đến cảm xúc của những người khác - và có một điều chắc chắn rằng, các INTJ gặp khó khăn khi thể hiện điều gì đó bằng cảm xúc.',
      'mqh4':'Những người mang loại tính cách INTJ thường là những cá nhân có năng khiếu và tỏa sáng, họ luôn tìm kiếm sự tăng trưởng và phát triển cá nhân, và cũng khuyến khích bạn bè của họ đi theo con đường tương tự. Nếu INTJ có thể kết nối với người khác ở mức độ này, tình bạn của họ có khả năng sẽ mạnh mẽ và lâu dài. Nói chung các INTJ thường là những người bạn "ít cần quan tâm", những người không đòi hỏi nhiều sự chú ý hoặc liên lạc thường xuyên - họ hiểu được giá trị của sự riêng tư và độc lập, và cũng sẽ thực sự giúp bạn bè của họ để trở nên độc lập hơn.',
      'mqh5':'Tóm lại, các INTJ tin vào sự phát triển bền vững trong các mối quan hệ, họ nỗ lực vì sự tự do cho bản thân và bạn bè của họ. Các INTJ liên tục bắt tay vào các dự án "cải tiến" nâng cao chất lượng tổng thể cuộc sống và các mối quan hệ của họ. INTJ rất nghiêm túc với những cam kết của họ, nhưng lại vui vẻ chấp nhận để xác định lại sự cam kết đó nếu họ cảm thấy việc gì đó có thể chứng minh là tiến bộ hơn so với hiểu biết hiện tại của họ. Họ không dễ dàng "cởi mở" và quá thân mật với bạn bè hoặc con cái, và đôi khi có vẻ như vô tâm với nhu cầu tình cảm của họ. Tuy nhiên, INTJ là những người rất có năng khiếu và thông minh, họ luôn phấn đấu để làm được điều tốt nhất, và luôn phát triển theo hướng tích cực. Nếu họ áp dụng các mục tiêu cơ bản này vào mối quan hệ cá nhân, có khả năng INTJ sẽ tận hưởng những mối quan hệ tốt đẹp và hạnh phúc với gia đình và bạn bè.'
    },
    {
      'tinhcach':'INTP',
      'mqh1':'Các INTP rất am hiểu, thông minh, nhưng rất khó để hiểu họ, và rất ít người có sự kiên nhẫn và quyết tâm để vượt qua lá chắn của INTP. Tâm trí của INTP không ngừng suy nghĩ với những ý tưởng, câu đố và các giải pháp - Ngược lại, giao tiếp với người lạ thực sự là phiền toái đối với INTP. Do đó, INTP có xu hướng rất kén chọn bạn bè - nếu người khác có những sở thích khác nhau đáng kể với INTP hoặc chỉ đơn giản là không thể đương đầu với dòng bất ý tưởng tận của họ, thì chắc rằng không thể trở thành bạn thân với INTP.',
      'mqh2':'Các INTP có một "vòng tròn" nhỏ những người bạn tốt. Nhiều loại tính cách tìm kiếm bạn bè để trò chuyện, hỗ trợ tinh thần, sự công nhận của xã hội,... Các INTP có xu hướng bỏ qua những điều tầm thường đó và điều này cũng tự nhiên hạn chế một nhóm bạn bè tiềm năng khác. Những người mang tính cách INTP thường bị thu hút bởi các nhóm NT khác, những người cùng họ chia sẻ niềm đam mê thảo luận lý thuyết và các câu đố trí tuệ. Điều đáng nói là các INTP sẽ đánh giá cao và tôn trọng bạn bè của họ rất nhiều, và làm việc chăm chỉ để giữ cho các mối quan hệ bền vững hơn.',
      'mqh3':'Các INTP thường không "ấm áp" hoặc giúp đỡ mọi người về mặt tình cảm. Nếu bạn gặp khó khăn, các INTP sẽ đưa ra các giải pháp hợp lý để giúp bạn, nhưng đừng mong đợi họ sẽ thấu hiểu cảm xúc của bạn hoặc biết cách để giải thích một điều gì đó bằng cảm xúc chứ không phải lý trí. Điều này không có nghĩa là INTP không có cảm xúc và chỉ nên được xem họ như đi bộ bách khoa toàn thư - hoàn toàn ngược lại, các INTP có thể có những tình cảm rất mạnh, nhưng chúng có thể bị kìm nén, ẩn giấu sâu bên trong, mọi người khó nhận biết được.',
      'mqh4':'Tình bạn của các INTP là rất rõ ràng, mạnh mẽ và chân thành, cả hai đều ko cố gắng kiểm soát lẫn nhau và ít khi có cảm xúc thái quá. Các INTP tán dương lòng trung thành và sự hiểu biết về những ý tưởng kích thích suy nghĩ, lời khuyên hợp lý và đáng tin cậy của bạn bè - không dễ để trở thành bạn thân của một INTP, nhưng nếu bạn có xu hướng cố gắng, bạn sẽ thấy rằng một mối quan hệ như vậy là đáng nỗ lực.',
      'mqh5':'Tóm lại, các INTP sống một cuộc sống bên trong tâm trí của họ, nơi tràn ngập sự tưởng tượng và náo động. Vì vậy làm cho thế giới bên ngoài dường như lu mờ với họ. Điều này khiến cho họ thiếu động cơ để hình thành và duy trì những mối quan hệ. Trong cuộc sống của mình, các INTP thường không mở rộng các mối quan hệ. Họ chỉ cần vài mối quan hệ thật thân thiết, những mối quan hệ mà họ thật sự quý trọng và nó có nhiều ảnh hưởng đến họ. Bởi trọng tâm sự chú ý của INTP chủ yếu là hướng nội, với mục đích là tìm kiếm sự rõ ràng trong từng ý tưởng trừu tượng, nên họ thường không thể đồng điệu với những cảm xúc và nhu cầu của người khác. INTP thường thấy khó khăn để hiểu rõ về người khác, và thường thu mình cho tới khi đối phương chứng tỏ rằng họ đáng được lắng nghe những suy nghĩ của INTP. Luôn đặt việc làm chủ kiến thức và sức mạnh của não bộ lên trên hết, họ sẽ chọn làm việc với những người mà họ cho là thông minh. Một khi INTP chịu bắt đầu một mối quan hệ nào đó, họ rất thành thật và chung thủy, từ đó hình thành nên sự gắn bó về mặt tình cảm thuần khiết và minh bạch rõ ràng. Các INTP thường không hứng thú hoặc không hiểu biết nhiều về những trò tán tỉnh liên quan tới những mối quan hệ. Tuy nghiên, nếu có vấn đề xảy ra mà INTP cho là không thể hòa giải được, họ sẽ từ bỏ mối quan hệ và không bao giờ quay lại nữa.'
    },
        {
      'tinhcach':'ISFJ',
      'mqh1':'Trong mối quan hệ, các ISFJ cực kỳ ấm áp, vị tha và trung thành. Họ không quá kén chọn khi nói đến tình bạn, miễn là người khác sẵn sàng kết bạn với họ trên một mức độ sâu sắc. Các ISFJ thường dựa vào bạn bè để được sự hỗ trợ về tinh thần, tu vấn, và trấn an, điều này làm cho họ dễ bị tổn thương, nhưng lại tạo cho cả hai người một cơ hội để thiết lập một mối quan hệ bền vững.',
      'mqh2':'Điều đáng nói, các ISFJ có thể gặp phải một vài vấn đề khi nói đến tình bạn. ISFJ thường đặt nhu cầu của bạn bè lên trên nhu cầu bản thân. Điều này chưa chắc là một điều xấu (với điều kiện là những người bạn không lạm dụng lòng vị tha của ISFJ), một cách tiếp cận như vậy có thể khiến cho ISFJ bỏ bê nhu cầu của họ. Các ISFJ cần rất nhiều hỗ trợ tinh thần từ bạn bè và nếu sự hỗ trợ này không đến từ bạn bè mà họ đã giúp, các ISFJ sẽ rất đau đớn.',
      'mqh3':'Thứ hai, các ISFJ thường "dính" vào cam kết của mình và làm hết sức mình để thực hiện lời hứa của họ. Đây là một đặc điểm rất lớn, nhưng kèm theo đó là ISFJ không muốn nói "không" khi bạn bè yêu cầu giúp đỡ. Một số người có thể xem đây là một điểm yếu và cố gắng lợi dụng thiện chí của ISFJ - các ISFJ nên giữ đặc điểm này trong vòng kiểm soát.',
      'mqh4':'ISFJ là những người sống hướng nội và họ không dễ cởi mở - tuy nhiên, họ cần vài người bạn thân để thảo luận về các vấn đề quan trọng. Các ISFJ không thích kết bạn với những người mang đặc điểm T hay P , họ thích kết bạn với người mang đặc điểm FJ. Thật ngạc nhiên khi ISFJ cũng có thể có ít nhất một người bạn thuộc loại trực giác N, mặc dù họ có thể gặp khó khăn trong việc kết nối do sự khác biệt giữa loại S và N.',
      'mqh5':'Tóm lại, Các ISFJ rất coi trọng các mối quan hệ cá nhân. Họ thường quan tâm và dành nhiều tình cảm cho người khác và đặt nhu cầu của họ lên trên nhu cầu của mình. Họ rất tận tình và luôn tìm kiếm mối quan hệ lâu dài. Họ là những người đáng tin cậy và luôn cố gắng hết mình để đảm bảo cho mọi việc diễn ra tốt đẹp. Các ISFJ thường khó từ chối giúp đỡ người khác vì vậy họ thường xem việc giúp đỡ người khác là điều hiển nhiên.'
    },
    {
      'tinhcach':'ISFP',
      'mqh1':'Các ISFP có xu hướng thoải mái và tự nhiên, tận hưởng cuộc sống trong hiện tại và không phải lo lắng nhiều về các kế hoạch dài hạn hoặc các cuộc tranh luận nghiêm trọng. Không ngạc nhiên, những người có loại cá tính này có xu hướng bị thu hút, và thu hút những người thích sự ngẫu hứng, các hoạt động hoặc sở thích nghệ thuật hay giải trí chứ không phải là mưu cầu trí tuệ. Các ISFP cũng ít kết bạn thân thiết với những người thích cấu trúc, môi trường an toàn - ISFP cần phải có rất nhiều sự tự do và không gian riêng.',
      'mqh2':'Mặt dù các ISFP thích sự ngẫu hứng và lối sống thoải mái nhưng họ vẫn là người hướng nội. Cho dù họ biết cách làm thế nào để vui chơi cùng những người bạn, nhưng ISFP có thể sẽ rất riêng tư hoặc thậm chí nhút nhát khi gặp người lạ. Đây là cơ chế bảo vệ tự nhiên của họ - những người có loại tính cách này rất nhạy cảm và có thể miễn cưỡng cởi mở lần đầu tiên. Các ISFP có xu hướng che dấu một phần cảm xúc hay hành động cá nhân, ví dụ như nếu hành vi hay thói quen của họ đang bị chỉ trích bởi bạn bè của họ - hậu quả là họ làm hết sức mình để che chắn cảm xúc nhạy cảm của tính cách họ từ những người mà họ không hoàn toàn tin tưởng.',
      'mqh3':'Các ISFP rất ấm áp, giúp đỡ và khoan dung với bạn bè. --- .Tuy nhiên, các ISFP cần phải biết rằng bạn bè của họ sẵn sàng trả ơn bằng cách hỗ trợ chứ không phải là chỉ trích họ. Tính cách của ISFP là không thích bị ràng buộc bởi các quy tắc, truyền thống hoặc kỳ vọng, và không thể chịu được những người giảng dạy cho họ về cách mà họ nên sống cuộc sống như thế nào.',
      'mqh4':'Điều đáng nói đến là các ISFP tin vào hành động không cần lời nói - những thứ mà nó bắt nguồn từ thực tế, và họ quan tâm đến những thứ chắn chắn chứ không phải là có thể, nên hay sẽ được. Đây là lý do chính khiến cho các ISFP mang đặc điểm S chứ phải là N - trực quan.',
      'mqh5':'Điều đáng nói đến là các ISFP tin vào hành động không cần lời nói - những thứ mà nó bắt nguồn từ thực tế, và họ quan tâm đến những thứ chắn chắn chứ không phải là có thể, nên hay sẽ được. Đây là lý do chính khiến cho các ISFP mang đặc điểm S chứ phải là N - trực quan.'
    },
    {
      'tinhcach':'ISTJ',
      'mqh1':'Trong các mối quan hệ, ISTJ có thể không trìu mến hay nói nhiều, nhưng họ chắc chắn sẽ rất trung thành và đáng tin cậy. Những người có loại cá tính này thường tiếp cận mọi thứ một cách chậm rãi và có phương pháp - và điều này bao gồm cả trong tình bạn của họ. Một ISTJ có thể rất chậm khi đưa ra lời hứa, nhưng một khi họ đã hứa, họ sẽ làm mọi thứ có thể để đáp ứng các cam kết của họ. Danh dự và lòng trung thành là rất quan trọng đối với ISTJ, đặc biệt là với những người bạn thân thiết.',
      'mqh2':'Các ISTJ khá nhạy cảm với những bạn bè thân thiết, mặc dù họ có thể cảm thấy khó khăn để thể hiện tình cảm. ISTJ thích truyền đạt cảm xúc đó thông qua những nỗ lực của họ chứ không phải lời nói. Các ISTJ sẽ không quan tâm thư giãn và vui đùa với những người hướng ngoại.',
      'mqh3':'Các ISTJ thường tìm kiếm những người bạn có chung các nguyên tắc và quan điểm. Do đó, họ thường hướng về phía những người mang nhóm SJ. ISTJ không kín đáo, và họ chắc chắn có thể hiểu và đánh giá cao những thế mạnh của người khác, tuy nhiên ISTJ vẫn không thu hẹp khác biệt để kết bạn với những người khác cho dù hiểu rõ về họ. Đáng ngạc nhiên, ISTJ có xu hướng hình thành tình bạn mạnh mẽ với loại N , mặc dù các rào cản SN đôi khi là quá khó khăn để vượt qua.',
      'mqh4':'Các ISTJ là những người đứng đầu trong các loại tính cách về việc thể hiện nỗ lực của mình. Nếu mục tiêu của ISTJ là mối quan hệ thì bạn hãy tin rằng các ISTJ sẽ làm tất cả để duy trì và phát triển mối quan hệ đó.',
      'mqh5':'Tóm lại, ISTJ là người trọng danh dự và uy tín, họ luôn giữ lời hứa và tuyệt đối thực hiện đúng cam kết của mình. Vì vậy họ rất cẩn thận và nghiêm túc khi đưa ra lời hứa, một khi đã nói “Anh/ Em đồng ý” có nghĩa là họ chấp nhận mối quan hệ cho đến “cái chết chia lìa chúng ra”. Các ISTJ luôn khát khao hoàn thành tốt nhiệm vụ và nghĩa vụ của mình, họ làm với tất cả khả năng và nhiệt huyết của mình.Cho dù ở vị trí nào họ vẫn cố gắng làm tròn nghĩ vụ của mình như làm: Chồng - vợ, Cha-mẹ, con cái, lãnh đạo-nhân viên,…Các ISTJ thường gặp khó khăn khi bộc lộ tình cảm nhưng họ có thể thể hiện bằng hành động.'
    },
    {
      'tinhcach':'ISTP',
      'mqh1':'ISTP là những người bạn rất toàn diện và thú vị, sống trong hiện tại và thưởng thức bất cứ điều gì mà cuộc sống mang lại cho họ. Phương châm của họ là "tất cả mọi thứ có thể thay đổi". Tình bạn với ISTP giống như một tàu lượn siêu tốc - nó thực sự rất thú vị và thỏa mãn trong ngày, và cảm giác hoàn toàn trái ngược vào ngày hôm sau. Tính cách ISTP là không thích cam kết, nhìn thấy mối quan hệ của họ như là một cái gì đó có thể thay đổi mỗi ngày.',
      'mqh2':'Các ISTP hiếm khi gặp khó khăn trong việc kết bạn - họ thích theo đuổi nhiều sở thích khác nhau, do đó họ có thể nghĩ ra rất nhiều điều thú vị để làm, vì vậy việc kết bạn với họ thật dễ dàng. Các hoạt động chung hình thành cơ sở tình bạn ISTP - những người mang loại cá tính này có khả năng kiểm soát tuyệt vời tất cả năm giác quan và thích thú cạnh tranh với những người khác, cách dễ nhất để trở thành một người bạn với ISTP là tìm một sở thích chung (tốt nhất là về thể chất).',
      'mqh3':'Các ISTP có xu hướng bị thu hút bởi những người mang đặc điểm S mạnh, vì họ có xu hướng là người đầu tiên khám phá ra các trải nghiệm mới. Ngược lại, với loại N (trực quan), có thể làm cho ISTP hơi khó chịu, vì ISTP thường gặp khó khăn khi tìm hiểu những ý tưởng trừu tượng của họ. Tuy nhiên, nếu tình bạn chủ yếu xoay quanh một sở thích chung, các ISTP vẫn sẽ chấp nhận một người nào đó dù có nhiều quan điểm khác nhau. Nói chung, ISTP khá cởi mở và thoải mái trong các mối quan hệ, và không có gì ngạc nhiên khi họ có xu hướng được nhiều người ưa thích.',
      'mqh4':'Tóm lại, các ISTP có khả năng làm việc độc lập và hoàn thành tốt những điều làm họ thích thú. ISTP là những người có tư tưởng thông thoáng, thú vị và hấp dẫn. Họ sống trong hiện tại và thường không lo nghĩ đến tương lai. Các ISTP thường quan niệm "không có gì là tuyệt đối", họ thích phát triển mối quan hệ từng bước một hơn là đưa ra những cam kết về một mối quan hệ lâu dài. Nếu mối quan hệ làm họ hứng thú và thoả mãn yêu cầu của họ, ISTP sẽ không ngững hoàn thành nghĩa vụ để giữ gìn mối quan hệ bền vững. Nếu họ cảm thấy không hứng thú thì họ sẽ có xu hướng bỏ qua, và tìm kiếm mối quan hệ mới phù hợp hơn.',
      'mqh5':''
    },
  ];
  int get getResult{
    int id;
    if (result =="ENFJ") {
      id = 0;
    } else if (result =="ENFP") {
      id = 1;
    } else if (result =="ENTJ") {
      id =2;
    } else if (result =="ENTP") {
      id = 3;
    } else if (result =="ESFJ") {
      id = 4;
    }else if (result =="ESFP") {
      id = 5;
    } else if (result =="ESTJ") {
      id = 6;
    } else if (result =="ESTP") {
      id = 7;
    } else if (result =="INFJ") {
      id = 8;
    } else if (result =="INFP") {
      id = 9;
    } else if (result =="INTJ") {
      id = 10;
    } else if (result =="INTP ") {
      id = 11;
    } else if (result =="ISFJ") {
      id = 12;
    }else if (result =="ISFP ") {
      id = 13;
    } else if (result =="ISTJ") {
      id = 14;
    }else {
      id = 15;
    }
    return id;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        padding:const EdgeInsets.all(8.0),
        child: ListView.builder(
          itemCount: 1,
          itemBuilder: (BuildContext context,_) {  
            return SingleChildScrollView(
              child: Column(
                children: [
                  TextDetail(moiquanhe[getResult]['mqh1'] as String),
                  const SizedBoxDetail(),
                  TextDetail(moiquanhe[getResult]['mqh2'] as String),
                  const SizedBoxDetail(), 
                  TextDetail(moiquanhe[getResult]['mqh3'] as String),
                  const SizedBoxDetail(),       
                  TextDetail(moiquanhe[getResult]['mqh4'] as String),
                  const SizedBoxDetail(), 
                  TextDetail(moiquanhe[getResult]['mqh5'] as String),
                ],
              ));
          },
          
        ),
    );
  }
}