import 'package:flutter/material.dart';
import 'package:fluttter_quiz_app/widgets/sizedbox.dart';
import 'package:fluttter_quiz_app/widgets/text.dart';

class SuNghiep extends StatelessWidget {
  SuNghiep({ Key? key, required this.result }) : super(key: key);
  final String result;

  final sunghiep = [
    {
      'tinhcach':'ENFJ',
      'sunghiep1' :'Hầu hết sự nghiệp điển hình của ENFJ đều có chung một đặc điểm quan trọng đó là tập trung vào việc làm cho người khác hạnh phúc. Các ENFJ thường rất ấm áp, gần gũi và vị tha, họ có nhiều sự lựa chọn khả thi khi nói đến việc chọn một nghề nghiệp tốt nhất cho họ.',
      'sunghiep2' :'Chúng ta hãy bắt đầu khỏa sát sự lựa chọn nghề nghiệp của ENFJ bằng cách chỉ rõ một thực tế là ENFJ chân thành quan tâm đến người khác và cố gắng làm hết sức mình để giúp đỡ mọi người. Trên hết, những người mang loại tính cách ENFJ có xu hướng có kỹ năng xã hội và giao tiếp phi thường \n- ENFJ được gọi là "Người thấu hiểu mọi người". ENFJ tỏa sáng trong các lĩnh vực cần sự tiếp xúc với khách hàng \n- họ có thể trở thành đại diện bán hàng suất sắc, chuyên gia tư vấn quảng cáo hoặc quản trị nhân sự.',
      'sunghiep3' :'ENFJ thường khá nhạy cảm và thậm chí có phần duy tâm. Đây là một con dao hai lưỡi, bởi vì sự nhạy cảm hướng ENFJ đến với lĩnh vực cần trí tuệ cảm xúc cao, mặt khác ENFJ rất dễ bị chỉ trích và nên tránh xa các công việc căng thẳng. Một số ngành nghề mà ENFJ nên tránh: tài chính (đặc biệt là kinh doanh chứng khoán), cảnh sát, quản lý của công ty, nhân viên cấp cứu, y học hay quân sự.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Đặc biệt giỏi trong việc đối nhân xử thế\n- Coi trọng cảm xúc của mọi người\n- Chân thành và nhiệt tình quan tâm đến mọi người\n- Trung thành và trung thực\n- Lấy việc giúp đỡ người khác làm niềm vui cho bản thân mình\n- Đánh giá cao cấu trúc và tổ chức',
      'goiynghe':'- Chính trị gia / Nhà ngoại giao,Nhà tâm lý học, Công tác xã hội / Cố vấn,Nhà giáo,Nhà tư vấn, Quản lý nhân sự, Đại diện bán hàng, Tổ chức sự kiện, Nhà văn.',
    },
    {
      'tinhcach':'ENFP',
      'sunghiep1' :'Các ENFP là những người có kỹ năng xã hội tuyệt vời và nhận thức đáng kinh ngạc. Loại tính cách ngày vượt trội khi nói đến sự kết nối mọi người và tìm kiếm những gì làm nên dấu hiệu của người khác \n- đây là một kỹ năng tuyệt vời trong bất kỳ nghề nghiệp. Hơn nữa, các ENFP có một khả năng độc đáo để giao tiếp với những người khác trên mức độ của riêng họ \n- Điều này cho phép họ tạo ra các mối quan hệ mạnh mẽ, lâu dài. Do những đặc điểm này, sự nghiệp ENFP điển hình liên quan đến rất nhiều sự tương tác cá nhân và đòi hỏi kỹ năng xã hội tốt \n- ví dụ, ENFP có thể trở thành các nhà tâm lý tuyệt vời, giáo viên, nhân viên tư vấn, các nhà ngoại giao hay chính trị gia.',
      'sunghiep2' :'Các ENFP rất có năng khiếu, năng động, định hướng được tương lai. Họ có thể dễ dàng cạnh tranh với các nhóm tính cách khác trong lĩnh vực nghề nghiệp khi nói đến việc nhìn thấy một bức tranh lớn hơn hay tìm kiếm các nguyên tắc cơ bản. Hơn nữa, mặc dù là một loại F, ENFP vượt trội khi sử dụng tu duy logic của họ, tạo thành một sự kết hợp rất mạnh giữa trực giác và lý trí \n- họ có thể tập trung vào các mục tiêu chính và sau đó sắp xếp, lên kế hoạch để đạt được mục tiêu đó. Có rất nhiều sự nghiệp tiềm năng tận dụng tốt những đặc điểm ENFP \n- những người có cá tính này có xu hướng phân tích hệ thống nhiều mặt, các nhà khoa học, kỹ sư và doanh nhân. Đây là những nơi mà ENFP thực sự có thể tỏa sáng \n- ví dụ, các nhà khoa học và kỹ sư với hệ thống mạng lớn.',
      'sunghiep3' :'Những yếu điểm này có thể cản trở sự tiến bộ của họ trong một số lĩnh vực \n- tuy nhiên, một số ENFP biến chúng thành điểm mạnh. Ví dụ, ENFP làm rất tốt trong các công việc như văn bản, báo chí, diễn xuất hay báo cáo truyền hình \n- công việc như vậy có thể đảm bảo rằng các ENFP không bao giờ hết những ý tưởng thú vị và có một lượng khán giả lớn để giữ chúng trong một thời gian dài.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Kĩ năng giao tiếp và viết lách tốt.\n- Nhiệt tình, đặt nhu cầu của người khác lên trên nhu cầu của mình.\n- Thân thiện, quan tâm đến mọi người, khả năng giao tiếp tốt.\n- Thông minh và bản lĩnh.\n- Có nhiều mục tiêu ngắn hạn.\n- Có khả năng liên kết với người khác.\n- Rất mạnh trong việc dùng trực giác và cảm giác để đánh giá người khác.\n- Không thích người khác điều khiển mình.',
      'goiynghe':'- Chính trị gia/ Nhà ngoại giao, Chuyên viên tư vấn, Nhà văn/ Nhà báo, Bác sĩ tâm lý, Diễn viên, Doanh nhân.\n- Luật sư.\n- Nhà giáo, Phóng viên, Khoa học gia/ Kĩ sư, Lập trình viên, chuyên gia phân tích hệ thống hoặc chuyên gia máy tính.',
    },
    {
      'tinhcach':'ENTJ',
      'sunghiep1' :'Sự nghiệp điển hình của ENTJ được xác định bởi vài đặc điểm mà hầu hết mọi người tiếp xúc với ENTJ đều có thể nhận ra đó là: nghị lực, quyết tâm và lãnh đạo. Những đặc điểm này có xu hướng đẩy ENTJ hướng tới một vài nghề nghiệp nhất định và cũng hạn chế phần nào sự lựa chọn của họ, tuy nhiên, những người có loại tính cách này không hề luyến tiếc về điều đó.',
      'sunghiep2' :'ENTJ rất thích việc chuyển các ý tưởng thành kế hoạch hành động, đây là một trong những ưu điểm của họ cũng là những nghề nghiệp điển hình mà họ chú tâm tới. Họ hướng đến tương lai và có một mức độ tự tin hiếm thấy so với các nhóm tính cách khác. Những đặc điểm này khiến cho ENTJ xuất sắc trong các vị trí: giám đốc điều hành, doanh nhân, chiến lược gia của công ty \n- họ sẽ có đủ nghị lực và quyết tâm để triển khai một ý tưởng ngay cả khi có nhiều trở ngại trong con đường của mình.',
      'sunghiep3' :'ENTJ là một người giao tiếp xuất sắc (đặc biệt là bằng lời nói), họ thích cấu trúc và trật tự, nhưng rất ghét nhiệm vụ thường nhật. Điều này có nghĩa là ENTJ có tầm nhìn xa trông rộng, họ phù hợp với vị trí lãnh đạo chứ không phải là vị trí quản lý hay quản trị công việc ngày qua ngày. Sự nghiệp điển hình của ENTJ phải có liên quan đến lãnh đạo. Có một điều chắc chắn rằng, ENTJ không bao giờ chấp nhận một ví trí nhân viên cấp thấp trong một thời gian dài.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Nhà lãnh đạo bẩm sinh\n- Muốn mọi thứ phải luôn có tổ chức, ngăn nắp và kỷ luật\n- Luôn muốn biến lý thuyết thành thực tiễn\n- Tự tin vào bản thân\n- Có kiến thức sâu rộng\n- Khả năng giao tiếp xuất sắc\n- Không thích sự kém hiệu quả và bất tài\n- Định hướng tương lai rõ ràng\n- Rất quyết đoán',
      'goiynghe':'- Doanh nhân, Xây dựng tổ chức/doanh nghiệp/công ty,Giám đốc điều hành,Quản trị doanh nghiệp,Cố vấn về máy tính,Quan tòa, luật sư, Giảng viên',
    },
        {
      'tinhcach':'ENTP',
      'sunghiep1' :'ENTP là loại tính cách linh hoạt nhất, danh sách ngành nghề của họ rất phong phú. Các ENTP có kỹ năng xoay chuyển tình thế nhanh và mạnh mẽ, mang đến cho họ một lợi thế khác biệt trên các nấc thang sự nghiệp \n- miễn là họ hiểu điểm mạnh và điểm yếu của họ. Bài viết này sẽ thảo luận về những công việc tốt nhất cho ENTP \n- Ý kiến, góp ý hay chỉ trích của bạn luôn được chào đón.',
      'sunghiep2' :'Các ENTP thực sự rất yêu thích sự sáng tạo ra ý tưởng mới và đề ra các dự án mới. Đây là một trong những tính cách sáng tạo và linh hoạt nhất và những đặc điểm như vậy luôn được nhìn thấy rõ ràng, bất kể con đường sự nghiệp nào mà ENTP lựa chọn. Trí thông minh của họ thậm chí có thể hơi đáng sợ, các ENTP có một sự kết hợp bùng nổ của hướng ngoại ( E ), khuynh hướng cho các mục đích hữu trí tuệ ( NT ) và tự phát ( P ). Những đặc điểm đó đã đẩy ENTP hướng đến những lĩnh vực cho phép họ sử dụng những luồn ý tưởng một cách hiệu quả \n- ví dụ, ENTP có xu hướng trở doanh nhân xuất sắc, diễn viên hay kỹ sư.',
      'sunghiep3' :'Các ENTP có kỹ năng giao tiếp rất tốt (cả nói và viết) và cũng có một số thứ khiến họ thích thú hơn việc tranh luận với ý tưởng của người khác. Điều thú vị và các ENTP cũng có khả năng lãnh đạo tốt, nhưng họ không thích quản lý người khác hay bị người khác quản lý. Mặt khác, những người có loại cá tính này có thể dễ dàng động viên và truyền cảm hứng cho những người khác, mặc dù nguồn cảm hứng đó đến từ lý trí và trí tuệ chứ không phải là cảm xúc. Một số ngành nghề điển hình mà ENTP có thể tận dụng tốt những đặc điểm bí ẩn:luật sư, nhà tâm lý học, các nhà khoa học hay thậm chí đại diện bán hàng, miễn là họ có đủ tự do.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Thích tranh luận với người khác.\n- Sáng tạo và khéo léo.\n- Linh hoạt và đa dạng.\n- Thích đưa ra dự án.\n- Thích đưa ra ý tưởng và giả thuyết.\n- Logic, là người suy nghĩ có lý lẽ.\n- Lanh lợi và có năng lực.\n- Thích giải quyết những vấn đề khó khăn.\n- Có khả năng giao tiếp tuyệt vời.\n- Đề cao kiến thức và năng lực.\n- Kĩ năng đối nhân xử thế tuyệt vời.',
      'goiynghe':'- Nhà tâm lý học, Luật sư, Cố vấn, Doanh nhân, Nhà khoa học, Kỹ sư,Thợ chụp ảnh, Nhân viên đại diện bán hàng,Diễn viên,Tiếp thị cá nhân,Lập trình viên, chuyên gia máy tính, nhà phân tích cấu trúc dữ liệu.',
    },
    {
      'tinhcach':'ESFJ',
      'sunghiep1' :'Chúng ta bắt đầu viết về những nghề nghiệp tiêu biểu của ESFJ theo ba đặc trưng: thực tế, vị tha và hòa đồng. Những công việc mà ESFJ chọn có xu hướng phản ảnh đến các đặc trưng đó là tốt \n- những người có tính cách này hướng ngoại tuyệt đối và tính cảnh giác cao (SJ), những đặc điểm này thường được thể hiện rõ ràng và đẩy họ về phía con đường sự nghiệp nhất định.',
      'sunghiep2' :'Các ESFJ rất có tổ chức, đáng tin cậy và là những con người thực tế. Họ rất phấn khởi trong việc làm cho môi trường của họ có cấu trúc hơn và dễ dự đoán. Họ không né tránh các công việc đơn điệu, thường nhật. Một số các con đường sự nghiệp tốt nhất cho ESFJ xoay quanh những đặc điểm này là nhân viên kế toán xuất sắc, kế toán hoặc quản trị viên.',
      'sunghiep3' :'Các ESFJ thực sự cần cảm thấy được đánh giá cao và được mọi người biết là họ đã giúp một ai đó. Những người có loại cá tính này thấy khó để hài lòng với công việc mà nếu họ không tin rằng họ đang tạo ra một số giá trị và trao nó cho người khác. Đặc điểm này là một động lực đằng sau nhiều sự nghiệp điển hình của ESFJ, đặc biệt là nếu họ đang ở trong các lĩnh vực công tác tôn giáo, xã hội hay tâm lý.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Cảm thấy hài lòng khi cho đi.\n- Có tổ chức.\n- Đáng tin cậy.\n- Thực tế.\n- Trung thành.\n- Ấm áp và dễ cảm thông.\n- Thích sáng tạo trật tự, cấu trúc và thời khóa biểu.\n- Có xu hướng ưu tiên nhu cầu của người khác.\n- Thích gây ảnh hưởng với những người khác.\n- Rất hợp tác, là một thành viên tốt khi làm việc nhóm.',
      'goiynghe':'- Cố vấn/ Công tác xã hội,Thủ thư/ Kế toán, Chăm sóc sức khỏe tại gia,Y tá,Chăm sóc trẻ em,Lãnh đạo,Giáo viên\n- Trưởng phòng, Tăng lữ hoặc những việc liên quan đến tôn giáp,Trợ lí giám đốc, Kinh doanh hộ gia đình',
    },
    {
      'tinhcach':'ESFP',
      'sunghiep1' :'Các đặc điểm quan trọng nhất được chia sẻ bởi các ESFP là ham muốn sự phấn khích, kích thích và mới lạ. Những người có loại cá tính này tìm kiếm những thách thức mới, có niềm vui trong xã hội với nhiều người khác nhau, và luôn luôn tập trung vào hiện tại. Một số nghề nghiệp tốt nhất cho các ESFP tập trung vào những đặc điểm này \n- ví dụ, ESFP có xu hướng trở thành nghệ sĩ tuyệt vời, nhiếp ảnh gia, các nhà hoạch định sự kiện và đại diện bán hàng.',
      'sunghiep2' :'Các ESFP thực sự quan tâm đến người khác và họ biết làm thế nào để làm cho mọi người hài lòng, ngay cả trong những tình huống khó khăn. Như đã đề cập ở trên, ESFP có thể rất tháo vát, đặc biệt là khi sự giúp đỡ của họ là rất cần thiết. Tiếp xúc với người khác là rất quan trọng cho loại tính cách này và gần như tất cả các con đường sự nghiệp của ESFP được dựa trên nhu cầu này \n- ESFP có thể là nhà cố vấn tuyệt vời và tạo cảm hứng, nhân viên xã hội, huấn luyện viên cá nhân, tư vấn, ...',
      'sunghiep3' :'Nói chung, đây là những điều quan trọng cần nhớ trong sự nghiệp của các ESFP: họ cần rất nhiều sự tiếp xúc với những người khác, nhiều hơn so với bất kỳ loại tính cách khác; cơn khát của họ cho những thách thức mới là không thể tắt, và họ cần phải cảm thấy rằng công việc của họ đang được đánh giá cao bởi những người khác.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Kĩ năng giao tiếp tốt.\n- Sống với hiện tại.\n- Ghét phải theo khuôn mẫu và sự sắp đặt.\n- Biết cách tận hưởng niềm vui, và biết làm cách nào để tạo niềm vui cho người khác.\n- Dễ bị kích thích và hứng thú bởi những trải nghiệm mới.\n- Không thích lý thuyết và các giải thích dài dòng.\n- Yêu thích mọi người một cách chân thành.\n- Thực tế và thiết thực.',
      'goiynghe':'- Tư vấn tâm lý/ Công tác xã hội, Nghệ sĩ, người biểu diễn và diễn viên,Thiết kế thời trang, Đại diện bán hàng, Chuyên gia tư vấn, Chăm sóc trẻ em, Nhiếp ảnh gia, Trang trí nội thất.',
    },
        {
      'tinhcach':'ESTJ',
      'sunghiep1' :'Thứ nhất, nền tảng của tính cách và sự nghiệp của các ESTJ là sự tôn trọng sâu sắc đối với truyền thống, tính ổn định và sự an toàn. Các ESTJ rất trung thành và đáng tin cậy \n- những người có loại tính cách này sẽ làm tất cả mọi thứ để đáp ứng các cam kết và thực hiện các nhiệm vụ của họ. Không ngạc nhiên, khi một số các nghề nghiệp tốt nhất và phổ biến nhất của ESTJ là trong quân đội, cảnh sát hoặc các lĩnh vực pháp lý. Đó là lý do do tại sao các ESTJ thường được gọi là "công dân kiểu mẫu" \n- và họ làm hết sức mình để định hướng và duy trì hình ảnh này trong suốt sự nghiệp của họ.',
      'sunghiep2' :'Thứ hai, các ESTJ vốn có có nhiều đặc điểm lãnh đạo và thật sự họ rất thích việc tổ chức mọi người. Nguyên tắc và các giá trị bên trong của họ được diễn tả rất rõ ràng. Hơn nữa, các ESTJ không ưa vô tổ chức và sự thiếu khả năng \n- những đặc điểm này làm cho họ trở nên đáng sợ, nhưng có hiệu quả cao trong những giai đoạn quản lý sau này của sự nghiệp họ. Các ESTJ cũng thích đưa ra cấu trúc mới ngay tại chỗ và họ cũng khá kỹ lưỡng. Những đặc điểm này làm cho các ESTJ tỏa sáng trong các vị trí: quản trị kinh doanh, kiểm toán viên và quan chức tài chính trong thế giới doanh nghiệp \n- các nghề nghiệp như vậy hay tương tự là sự lựa chọn tuyệt vời cho các ESTJ. Có lẽ hơi ngạc nhiên, các ESTJ cũng có xu hướng trở thành đại diện bán hàng tốt.',
      'sunghiep3' :'Cuối cùng, các nghề nghiệp tốt nhất cho các ESTJ là tận dụng tốt sự chăm chỉ, trung thực và khả năng động viên mọi người. Các ESTJ thường kiên trì gắn bó với dự án cho đến khi nó hoàn thành, khó khăn không phải là vấn đề đối với họ. Những đặc điểm này là rất quan trọng khi nói đến sự thăng tiến trong sự nghiệp \n- .',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Thích thú trong việc xây dựng trật tự và cấu trúc.\n- Coi trọng an toàn và truyền thống.\n- Nhà lãnh đạo bẩm sinh – họ thích được dẫn đầu.\n- Có một hệ thống rõ ràng về những chuẩn mực và niềm tin.\n- Chăm chỉ và đáng tin cậy.\n- Trung thành.\n- Năng động và khỏe mạnh.',
      'goiynghe':'- Quản lý, Lãnh đạo quân đội, Quan tòa, Cảnh sát/ Thám tử,Nhân viên kế toán, Bán hàng, Nhà giáo',
    },
    {
      'tinhcach':'ESTP',
      'sunghiep1' :'Khi nói đến sự nghiệp, những người mang tính cách ESTP có một danh sách nghề nghiệp dài và đa dạng để lựa chọn. Những người mang loại tính cách này rất nhanh chóng đưa ra quyết định, do đó làm cho họ trở thành ứng viên xuất sắc cho vai trò đòi hỏi phải suy nghĩ tại chỗ \n- ví dụ: bán hàng, dịch vụ khẩn cấp, quản lý khủng hoảng, quân đội, cảnh sát... Điều này được củng cố thêm bởi thực tế là các ESTP sống trong giây phút hiện tại và muốn xem kết quả của hành động của họ ngay lập tức thay vì suy nghĩ về tương lai. Họ cũng có xu hướng rất quyến rũ và là những cá nhân xuất sắc trong việc liên kết mọi người \n- đặc tính như vậy có thể tạo cho họ một lợi thế lớn.',
      'sunghiep2' :'Tính cách của các ESTP cũng có xu hướng rất thiếu kiên nhẫn, có nghĩa là nghề nghiệp hay vai trò có liên quan đến việc nghiên cứu tỉ mỉ hoặc các nhiệm vụ lặp đi lặp lại không phải là phù hợp với họ. Các ESTP rất tinh ý và đặc điểm này có thể rất hữu ích trong một số lĩnh vực nhất định (ví dụ như bán hàng hoặc tiếp thị) \n- Nhưng bản chất tò mò và tràn đầy năng lượng của họ sẽ đẩy họ hướng tới hành động theo định hướng chứ không phải là vai trò phân tích. Các ESTP sẽ lựa chọn con đường sự nghiệp kém ổn định nhưng thú vị chứ không phải là chọn con đường sự nghiệp an toàn nhưng nhàm chán. Các ESTP thích chấp nhận các rủi ro, lớn và nhỏ, và thường sẽ là người thắng.',
      'sunghiep3' :'Những người mang tính cách ESTP có thể trở thành vận động viên xuất sắc. Họ có xu hướng rất cạnh tranh và năng động, đó là đặc tính tuyệt vời khi nói đến lĩnh vực thể thao. Các ESTP rất hào hứng bởi các hoạt động thể thao và một trong những cách tốt nhất để phát huy hết tất cả các năng lượng đó là trở thành một vận động viên chuyên nghiệp, một huấn luyện viên hoặc một nhà bình luận thể thao.',
      'sunghiep4' :'Để tìm kiếm chỗ đứng trong xã hội hay cần định hướng xem mình có đang đi đúng hướng hay không, thì điều quan trọng nhất là bạn cần phải hiểu chính mình và các đặc điểm tính cách có thể tác động đến thành công hay thất bại trong lĩnh vực bạn sẽ làm hay đang làm. Bạn cần phải biết được những gì có ý nghĩa hay quan trọng đối với bạn. Khi bạn hiểu được ưu điểm và nhược điểm của mình và nhận thức được điều quan trọng và ý nghĩa đối với cuộc đời bạn thì bạn sẽ chọn được nghề nghiệp phù hợp nhất với bản thân, toàn bộ thế mạnh của bạn sẽ được phát huy. Bạn sẽ thấy yêu công việc và cuộc sống hơn.',
      'dacdiem':'- Linh hoạt và thích ứng nhanh.\n- Sống với hiện tại.\n- Năng động.\n- Thích thấy kết quả do công việc mình làm ngay lập tức.\n- Không thích các lý thuyết trừu tượng mà không có ứng dụng thực tế.\n- Nhanh nhẹn và nhiều năng lượng.\n- Quan sát tốt.\n- Có khả năng độc lập ra quyết định.\n- Rất giỏi nhớ những chi tiết.\n- Ít khi làm việc theo kế hoạch – tới đâu hay tới đó.',
      'goiynghe':'- Lãnh đạo quân đội,Cảnh sát, Thám tử, Quan tòa, Nhân viên kế toán, Quản lý,Bán hàng, Nhà giáo,Các ngành nghề trong lĩnh vực thể thao.',
    },
      {
      'tinhcach':'INFJ',
      'sunghiep1' :'Có rất ít người mang tính cách này, chỉ chiếm khoảng 1% dân số và họ mang trong mình khá nhiều đặc điểm bất thường. Mặc dù sự hiện diện của họ có thể được miêu tả như là rất yên tĩnh, nhưng các INFJ lại thường có nhiều ý kiến ​​mạnh mẽ, đặc biệt là khi nói đến các vấn đề mà họ cho là thực sự quan trọng trong cuộc sống. Nếu một INFJ chiến đấu cho một điều gì đó thì nguyên nhân chính là vì họ tin vào ý tưởng riêng của mình, không phải vì một số lý do ích kỷ.',
      'sunghiep2' :'Tính cách của INFJ là hướng đến việc giúp đỡ những người đang cần \n- họ có thể vội vàng đến nơi một thảm họa lớn, tham gia vào nỗ lực cứu hộ, làm công việc từ thiện, ... Các INFJ coi đây là nhiệm vụ và mục đích của họ trong cuộc sống \n- những người có loại cá tính này vững tin rằng cách tốt nhất để giúp thế giới là loại bỏ tất cả các kẻ bạo ngược. Nghiệp chướng và các khái niệm tương tự là rất hấp dẫn đối với INFJ.',
      'sunghiep3' :'Những xu hướng đó cũng được củng cố bởi thực tế rằng tính cách của INFJ có một sự kết hợp độc đáo của chủ nghĩa lý tưởng và quyết đoán \n- điều này có nghĩa rằng sự sáng tạo và trí tưởng tượng của họ có thể được dẫn thẳng tới một mục tiêu cụ thể. Vài loại tính cách khác cũng có đặc điểm này và đây là một trong những lý do quan trọng nhất lý giải tại sao nhiều INFJ thực hiện ước mơ của họ và thực hiện một cách cương quyết lâu dài.',
      'sunghiep4' :'Các INFJ là bậc thầy về giao tiếp bằng văn bản, với một ngôn ngữ đặc sắc mượt mà và ấm áp. Ngoài ra, sự nhạy cảm của INFJ cho phép họ kết nối với những người khác khá dễ dàng. Giao tiếp dễ dàng và sự dễ chịu của họ thường có thể gây hiểu lầm cho những người xung quanh, những người đó có thể nghĩ rằng INFJ thực sự là hướng ngoại.',
      'dacdiem':'- Khả năng lãnh đạo tự nhiên.\n- Rất nguyên tắc.\n- Hiểu được con người và hoàn cảnh bằng trực giác.\n- Phức tạp và sâu sắc.\n- Duy tâm.\n- Hướng về tương lai.',
      'goiynghe':'- Giám mục , Các công việc liên quan đến tôn giáo, Bác sĩ , Nha sĩ,Nhà tâm lý học, Bác sĩ tâm thần,Giáo viên',
    },
        {
      'tinhcach':'INFP',
      'sunghiep1' :'Hầu hết các INFP có các nguyên tắc mạnh mẽ và các giá trị bên trong họ. Những người có loại tính cách này không ngừng nghỉ trong việc bảo vệ những ý tưởng mà họ tôn trọng và họ rất tận tâm với cả các cá nhân và nguyên nhân. Đặc điểm này là trọng tâm cốt lõi trong một số nghề nghiệp tốt nhất với INFP \n- ví dụ, các INFP có xu hướng trở thành nhà văn xuất sắc và khả năng thuyết phục của họ rất tốt khi viết về một nguyên nhân mà họ cho là quan trọng. Có rất nhiều nhà văn vĩ đại mang tính cách INFP \n- loại tính cách này có kỹ năng viết tốt nhất trong rất cả các nhóm tính cách. Nếu bạn là một INFP và chẳng hạn có một nghề nghiệp thu hút bạn, bằng mọi cách hãy thử nó, đặc biệt là kể từ khi internet cung cấp cho bạn một nền tảng tuyệt vời. Bạn có thể sẽ ngạc nhiên về công việc này.',
      'sunghiep2' :'Loại tính cách INFP là một trong số rất ít các nhóm tính cách có danh sách sự nghiệp lý tưởng bao gồm cả vị trí hướng đến phục vụ. Các INFP chân thành quan tâm đến người khác, cho dù người đó tốt hơn hay kém hơn họ, có xu hướng đặt mong muốn của người khác lên trên của mình. Kết hợp với sự sáng tạo, cá tính này làm cho các INFP trở thành nhà tư vấn khéo léo, nhân viên xã hội hoặc nhà tâm lý học. Một số ngành nghề điển hình khác có thể áp dụng những đặc điểm tính cách như vậy là rất tốt \n- nhiều INFP có thể được tìm thấy trong các học viện hoặc các ngành nghề khác có liên quan.',
      'sunghiep3' :'Các INFP có định hướng phát triển rõ ràng, nhưng họ cũng rất nhạy cảm và rất dễ bị chỉ trích. Điều này càng phức tạp hơn bởi họ có xu hướng làm việc một mình \n- các INFP không thấy thỏa mái đối với các nghề nghiệp có môi trường làm việc căng thẳng hoặc làm việc nhóm đã định hướng. Một số nghề nghiệp tốt nhất giúp INFP biến yếu điểm này thành một lợi thế lớn \n- ví dụ, các INFP thật sự cảm hứng khi trở thành một tín đồ tôn giáo, nhạc sĩ hoặc huấn luyện viên cá nhân. Những nghề nghiệp có xu hướng rất cá nhân và đòi hỏi rất nhiều nỗ lực cá nhân \n- điều này sẽ làm cho hầu hết các INFP rất hạnh phúc.',
      'sunghiep4' :'Nhìn chung, những người mang loại tính cách INFP là rất hiếm, phức tạp và bí ẩn \n- các INFP tìm kiếm nghề nghiệp mà nó không chỉ là việc làm, những người có loại tính cách này cần phải biết rằng những gì họ làm phải tạo ra tiếng vang lớn bằng các nguyên tắc cốt lõi và các giá trị bên trong họ. Như đã đề cập, có một vài sự nghiệp rất thích hợp cho INFP \n- họ chỉ đơn giản là cần phải tìm một nguyên nhân xứng đáng để tiến hành công việc đó.',
      'dacdiem':'- Thiên hướng phục vụ, đặt nhu cầu của người khác lên trên nhu cầu của mình.\n- Có hệ thống giá trị sống mạnh mẽ.\n- Trung thành và công hiến cho con người và chính nghĩa.\n- Quan tâm đến mọi người.\n- Dễ chịu và thoải mái, trừ phi có một nguyên tắc sống bị xâm phạm.\n- Hướng về tương lai.',
      'goiynghe':'- Nhà văn, Nhà tâm lý học, Giáo viên, Giáo sư, Cố vấn , Nhân Viên Xã Hội, Nhạc sĩ, Nhà tâm thần học.',
    },
    {
      'tinhcach':'INTJ',
      'sunghiep1' :'Các INTJ được biết đến với khả năng hấp thụ các lý thuyết khó và phức tạp có liên quan đến nghề nghiệp của họ, và sau đó chuyển hóa chúng thành các ý tưởng rõ ràng và hành động. Các INTJ là những nhà chiến lược xuất sắc, họ sở hữu trực giác và sự tự tin cho phép họ xây dựng và lên kế hoạch thực hiện thử thách trong dài hạn mà không có nhiều khó khăn. Những kỹ năng này có thể rất có giá trị trong con đường sự nghiệp đúng đắn \n- những người có loại tính cách này rất tuyệt vời khi làm những công việc có liên quan đến quy hoạch, chiến lược và áp dụng các nguyên tắc lý thuyết phức tạp. Ví dụ, bạn có thể tìm thấy nhiều INTJ trong quản lý dự án, kỹ sư hệ thống hoặc chiến lược tiếp thị. Đây thường là lựa chọn nghề nghiệp tốt nhất của họ.',
      'sunghiep2' :'Sự nghiệp điển hình của INTJ cũng có xu hướng đặt rất nhiều tầm quan trọng vào tư duy độc lập. Các INTJ thích những thách thức khó khăn và cực kỳ ghét công việc thường nhật, họ làm mọi thứ để tránh nó hoặc tìm cách tự động hóa nó. Họ nổi trội là "con sói cô độc" và sự nghiệp INTJ tốt nhất xoay quanh đặc điểm này, hãy cho INTJ đủ không gian linh hoạt để sự sáng tạo và cống hiến của họ không bị gián đoạn bởi các thành viên khác trong nhóm.',
      'sunghiep3' :'Những người có loại tính cách này đặt hiệu quả và năng lực lên trên mọi thứ khác. Do đó, các INTJ phù hợp nhất với các nghề nghiệp đòi họi sự sáng tạo và quyết đoán. Các INTJ cho rằng tất cả mọi người nên làm hết sức mình để hoàn thành nhiệm vụ với tiêu chuẩn cao nhất có thể và họ không thích những người tận dụng các mối quan hệ để thăng tiến trong sự nghiệp. Cách tốt nhất để mất đi sự tôn trọng của một INTJ với bạn là cho rằng kỹ năng xã hội và các mối quan hệ quan trọng hơn năng lực chuyên môn. Các INTJ có tiêu chuẩn rất cao, đặc biệt là khi nói đến việc riêng của họ và nỗ lực hết mình để hoàn thành nó. Do đó, những nghề nghiệp tiêu biểu của INTJ là có liên quan đến sự sáng tạo, cống hiến và đầy nhận thức(có cái nhìn sâu sắc trọn vẹn về điều gì đó).',
      'sunghiep4' :'Các INTJ hướng nội rất mạnh với các kỹ năng phân tích và sáng tạo tuyệt vời, họ rất không thích làm các công việc phải đối mặt với khách hàng hay phải làm việc nhóm đã được định hướng \n- những công việc như vậy không phù hợp với INTJ. Như đã đề cập, các INTJ là những chiến lược gia và lập kế hoạch xuất sắc, nhưng họ làm tốt nhất khi một mình hoặc theo nhóm nhỏ. Họ sẵn sáng phục vụ người khác nếu thấy người đó có năng lực hơn họ. Những INTJ mang đặc điểm này thường trở thành những kỹ sư xuất sắc, các nhà chiến lược quân sự, lập trình, phân tích hệ thống, luật sư hoặc chuyên gia tư vấn tự do. Đây là những con đường sự nghiệp điển hình của INTJ và hiệu suất của họ trong các lĩnh vực này thường là rất ấn tượng.',
      'dacdiem':'- Hiểu biết sâu rộng và trực giác tốt, và họ rất tin tưởng điều này.\n- Có xu hướng tạo ra trật tự và cấu trúc từ các lý thuyết trừu tượng.\n- Có khả năng tiếp thu các kiến thức và lý thuyết phức tạp.\n- Yêu thích các thử thách mang tính lý thuyết.\n- Là nhà chiến lược tối cao.\n- Đánh giá cao kiến thức và sự hiệu quả.\n- Có cái nhìn toàn cục, tổng thể.',
      'goiynghe':'- Nhà hoạch định chiến lược và xây dựng tổ chức công ty, Lãnh đạo quân đội\n- Nhà khoa học, Bác sĩ y khoa, nha sĩ, Kỹ sư',
    },
    {
      'tinhcach':'INTP',
      'sunghiep1' :'Các INTP rất yêu thích các phương pháp lý thuyết và ý tưởng. Sự nghiệp tốt nhất của INTP xoay quanh đặc điểm độc đáo này tạo ra một lợi thế rất lớn, vì có rất ít loại tính cách khác yêu thích lý thuyết nhiều như INTP. Vì lý do đặc biệt này, các INTP rất xuất sắc trong lĩnh vực nghiên cứu khoa học (đặc biệt là trong các lĩnh vực lý thuyết cao như vật lý hay hóa học), nhà toán học, thư ký kỹ thuật hoặc các nhà phân tích hệ thống.',
      'sunghiep2' :'Các INTP rất thích tìm kiếm và phân tích các nguyên tắc và ý tưởng cơ bản. Có nhiều con đường sự nghiệp điển hình cho phép INTP sử dụng đặc điểm này, thậm chí điều này thường đi kèm với ứng dụng thực tế mà thực sự không thu hút INTP. Ví dụ, các INTP có thể trở thành nhà chiến lược tuyệt vời của công ty, các nhà phân tích kinh doanh, nhà thiết kế video game, lập trình viên hoặc kỹ sư (nghề này đặc biệt thích hợp cho INTP do tình yêu của họ cho lý thuyết).',
      'sunghiep3' :'Các INTP có xu hướng rất độc lập (thậm chí có phần lập dị), luôn đặt tiêu chuẩn rất cao cho bản thân và không thích quản lý người khác hoặc bị quản lý, đặc biệt là trong sự nghiệp của họ. Đặc điểm này không hấp dẫn trong thế giới doanh nghiệp hiện đại và các INTP nên tránh đề cập đến chúng trong một cuộc phỏng vấn việc làm \n- tuy nhiên, nếu quản lý của họ tỏ ra là người sáng suốt và tư tưởng thông thoáng, thì INTP sẽ là một "máy phát" không biết mệt mỏi của những ý tưởng tuyệt vời và độc đáo. Một số ngành nghề tốt nhất cho INTP tận dụng tốt những đặc điểm này có thể là tập trung vào pháp lý, tư vấn tự do hay con đường nghiên cứu pháp y hoặc thí nghiệm.',
      'sunghiep4' :'Các INTP là "con sói cô độc" điển hình và sự nghiệp đặc trưng của INTP cũng xoay quanh đặc điểm này. Họ sống trong tâm trí của mình, yêu sự cô đơn và có xu hướng xem thường cuộc nói chuyện nhỏ và các nhu cầu thiết yếu xã hội khác. Các INTP không thực sự hiểu hoặc thích thú với việc giao lưu tình cảm và ít khi dành nhiều thời gian để chuyện trò với đồng nghiệp hoặc khách hàng của họ. Vì những lý do đó, các nghề nghiệp đối mặt với khách hàng được xem là rất không phù hợp với INTP \n- họ sẽ làm tốt hơn nhiều trong vị trí tập trung vào dữ liệu và lý thuyết chứ không phải là người. Ví dụ, các INTP có thể là luật sư xuất sắc, các nhà phân tích dữ liệu hoặc thậm chí là nhà báo, miễn là họ tìm thấy thú vị trong lĩnh vực đó \n- đây là một số những sự lựa chọn nghề nghiệp tốt nhất cho những người có loại tính cách này.',
      'dacdiem':'- Yêu thích lý thuyết và những ý tưởng trừu tượng.\n- Coi trọng kiến thức và năng lực hơn những thứ còn lại.\n- Người tìm kiếm sự thật – Họ luôn muốn hiểu rõ vấn đề bằng cách phân tích những nguyên tắc và cấu trúc tiềm ẩn bên trong.\n- Độc lập và lập dị, có thể gọi là khác người.\n- Có tiêu chuẩn rất cao về hiệu suất làm việc – điều mà họ luôn áp dụng cho chính mình.\n- Không thích những chi tiết nhàm chán.',
      'goiynghe':'- Nhà khoa học , đặc biệt trong nghiên cứu Vật Lí, Hóa Học, Chiến lược gia, Giáo sư đại học, Nhà Toán học, Nhiếp ảnh gia.',
    },
        {
      'tinhcach':'ISFJ',
      'sunghiep1':'ISFJ có xu hướng rất giỏi trong việc thu thập và ghi nhớ các sự kiện khác nhau, đặc biệt là về con người. Đây là một kỹ năng xã hội rất lớn trên con đường sự nghiệp. Đặc biệt là những nơi cần làm việc nhóm và sự hợp tác. ISFJ sẽ luôn luôn nhớ tên của con gái ông chủ hay ngày sinh nhật của hầu hết các đồng nghiệp của họ. Hơn nữa, ISFJ cũng rất đồng cảm với cảm xúc của người khác. Do đó, khi nói đến việc lựa chọn nghề nghiệp tốt nhất cho một ISFJ, có thể nói rằng họ có xu hướng trở thành nhà cố vấn tuyệt vời, trợ lý hành chính hoặc quản lý.',
      'sunghiep2':'Sự nghiệp của ISFJ có xu hướng tiến triển khá thuận lợi bởi vì ISFJ sẵn sàng đặt rất nhiều nỗ lực vào việc đảm bảo rằng công việc sẽ được hoàn thành. Họ rất thực tế \n- tuy nhiên, điều này đi kèm với một giá của nó, đó là ISFJ không thích các lý thuyết, khái niệm hoặc ý tưởng trừu tượng. Vì lý do này, các ISFJ nên tránh sự nghiệp liên quan đến lý thuyết (ví dụ như nghiên cứu học tập) và tập trung vào những lĩnh vực "thực tế" \n- họ thích thực thi các ý tưởng và làm mọi thứ hoạt động. Một số các con đường sự nghiệp điển hình nhất của ISFJ sử dụng các đặc điểm này: thiết kế nội thất, nhân viên kế toán, kinh tế hoặc quản lý văn phòng.',
      'sunghiep3':'Các ISFJ rất chuyên về phục vụ, ấm áp và truyền thống. Họ tôn trọng các giá trị truyền thống và sự an toàn \n- điều này cũng thường được phản ánh trong sự nghiệp ISFJ. Không phải là lạ khi nhìn thấy ISFJ tham gia vào các hoạt động tình nguyện, công tác cộng đồng hoặc các sáng kiến ​​phát triển thời thơ ấu. Họ cũng có xu hướng trở thành những y tá tuyệt vời và nhân viên xã hội hay tôn giáo.',
      'sunghiep4':'Nhìn chung, ISFJ cần phải sử dụng kỹ năng thấu hiểu cảm xúc con người bởi vì đây là một trong những điểm mạnh quan trọng nhất và độc đáo nhất của họ. Và ISFJ cũng cần tìm kiếm các cơ hội để tạo ra các nguyên tắc, trật tự từ sự hỗn loạn vì họ thường có tài năng thực sự đặc biệt trong lĩnh vực này. Con đường sự nghiệp của ISFJ sẽ phát triển rất tốt nếu ISFJ tận dụng được hai đặc điểm mạnh đó trong nghề nghiệp.',
      'dacdiem':'- Rất tinh ý và ý thức được cảm giác cũng như những phản ứng của người khác\n- Họ có một kho dữ liệu thông tin về người khác rất đa dạng và phong phú\n- Có trí nhớ tuyệt vời về những chi tiết mà họ thấy quan trọng\n- Có thể là chỗ dựa vững chắc, giúp đỡ mọi người hoàn thành nhiệm vụ của mình\n- Luôn có xu hướng giúp đỡ: tập trung vào các nhu cầu của người khác\n- Nhân hậu và chu đáo',
      'goiynghe':'- Chăm sóc trẻ em,Phát triển trẻ em, Nhà thiết kế, Trang trí nội thất, Y tá, Công tác xã hội,Cố vấn, Trợ lí giám đốc.',
    },
    {
      'tinhcach':'ISFP',
      'sunghiep1' :'Có khoảng 8% dân số mang tính cách này. Tính cách ISFP này thường được xem như là tự phát nhất và không thể đoán trước của tất cả các loại hướng nội. Đặc tính nổi bậc của họ đó là sự thay đổi',
      'sunghiep2' :'ISFP yêu thích khám phá và theo đuổi cái mới, những ý tưởng và hoạt động mới. Họ rất giỏi trong việc cảm nhận những cơ hội như vậy, nhưng các đặc điểm tính cách ISFP cũng đẩy họ hướng tới trải nghiệm và đến với những ý tưởng mà không ai nghĩ đến trước đây. Các ISFP thường khá dễ dàng để thiết lập xu hướng mới và truyền cảm hứng cho những người khác \n- sở thích trải nghiệm của họ là không giống với bất kỳ loại tính cách khác.',
      'sunghiep3' :'Một đặc tính nổi trội khác của ISFP là yêu thích sự tự do \n- các ISFP rất độc lập và quyết liệt chống lại tất cả các hình thức kiểm soát. Những người có loại tính cách này được xem là "linh hồn tự do" tối cao, họ xem tất cả các quy định, hướng dẫn và truyền thống như giới hạn tự áp đặt làm cho cuộc sống buồn tẻ và nhàm chán. Các ISFP sống hoàn toàn trong hiện tại, không bám vào quá khứ hoặc chuẩn bị kế hoạch mở rộng trong tương lai \n- họ lấy những thứ khi chúng đến, họ sẽ thử nghiệm và điều chỉnh hành vi khi cần thiết. ISFP không có khái niệm vô trách nhiệm hay thiếu thận trọng.',
      'sunghiep4' :'Các ISFP thực sự làm tuyệt vời trong các lĩnh vực đòi hỏi phải có một cách tiếp cận độc lập về nghệ thuật. Họ cũng có xu hướng rất quyến rũ, chủ yếu là vì họ nhận thấy nó thực sự dễ dàng để nhận được những lời khen tốt nhất \n- sự nhạy cảm( F ) và kiểm soát tuyệt vời của tất cả năm giác quan ( S ) của ISFP đã giúp họ rất nhiều trong việc hòa hợp giữa thế giới vật chất và tinh thần. Do đó, các ISFP hiếm khi có khó khăn khi kết nối với những người khác, mặc dù thực tế rằng họ là người sống hướng nội ( I ). Ngay cả khi ISFP đang thực sự không thể lường trước hoặc thậm chí liều lĩnh, sự quyến rũ của họ dễ dàng tước "vũ khí" của những người xung quanh.',
      'dacdiem':'- Sống thực tế.\n- Quan tâm đến môi trường sống và làm việc của mình.\n- Không thích giải quyết những vấn đề trừu tượng, trừ khi họ thấy được ứng dụng thực tế của nó.\n- Thích một cuộc sống chậm rãi – họ thích tận hưởng cuộc sống tại mọi thời điểm.\n- Nghiêm túc trong mọi việc, mặc dù họ thường không tỏ ra như vậy.\n- Là người độc đáo và có óc sáng tạo.',
      'goiynghe':'- Người làm công tác xã hội , Cố vấn, Nhà thiết kế\n- Nhà tâm lí học, Nhạc sĩ, Nghệ sĩ',
    },
    {
      'tinhcach':'ISTJ',
      'sunghiep1' :'ISTJ là loại tính cách phổ biến nhất, có đến 13% dân số trên thế giới thuộc nhóm tính cách này. Phương châm sống của họ là “Chỉ có sự thật”, tính cách của ISTJ là rất tôn trọng sự thật, họ có xu hướng tiếp thu rất nhiều thông tin và nhớ rất lâu.',
      'sunghiep2' :'Một trong những yếu tố góp phần quan trọng làm cho  ISTJ có khả năng phân tích các sự vật, hiện tượng, con người ở môi trường xung quanh rất tốt đó là nhờ đặc tính S.',
      'sunghiep3' :'Do cách tiếp cận thẳng thắn và trực tiếp nên ISTJ có thể gặp khó khăn khi tiếp cận các giả thuyết hoặc ý tưởng đối lập. Tuy nhiên các ISTJ sẽ quyết tâm tìm hiểu và thực hiện nếu biết ý tưởng đó là có giá trị và có thể thực hiện được – ISTJ sẽ cân nhắc trách nhiệm của họ để thiết lập và duy trì hoạt động ổn định. Ngay sau khi các ý tưởng mới chứng minh được tính hữu dụng của nó, các ISTJ sẽ nỗ lực hết mình để thực hiện thành công cho dù sức khỏe của họ bị tổn hại.',
      'sunghiep4' :'ISTJ rất kỹ lưỡng, luôn luôn kiểm tra các sự kiện và không giả định bất cứ điều gì.',
      'dacdiem':'- Làm việc trong thời gian dài và chăm chỉ để hoàn thành nhiệm vụ\n- Tôn trọng truyền thống, sự an toàn và một cuộc sống yên bình\n- Trung thành và thành thật\n- Có thể trông cậy trong việc hoàn thành nhiệm vụ\n- Coi trọng gia đình\n- Ổn định, thực tế và có óc xét đoán',
      'goiynghe':'- Thủ lĩnh quân đội, Thẩm phán.\n- Cảnh sát và thám tử, Luật sư, Kế toán và nhân viên tài chính.'
    },
    {
      'tinhcach':'ISTP',
      'sunghiep1' :'Có khoảng 5% dân số mang tính cách này, ISTP sở hữu nhiều đặc điểm thú vị có thể dễ dàng ngăn chặn người ngoài cuộc thăm dò họ. Họ thường rất lý trí và suy nghĩ logic, nhưng cũng có thể làm ngạc nhiên mọi người bằng cách đột nhiên trở nên tự phát và nhiệt tình nhiều hơn. Trong khi hầu hết các loại tính cách khác thường dễ dàng nhận biết và vạch ra rõ ràng những tính cách đặc trưng, thì điều này chắc chắn là không thể với trường hợp của ISTP \n- ngay cả những người quen biết họ cũng có thể không có khả năng dự đoán phản ứng của họ với một điều gì đó.',
      'sunghiep2' :'Điều này xuất phát từ sự kết hợp thú vị của lý trí ( T ) và sự linh hoạt ( P ) trong đặc điểm tính cách ISTP. Những người mang tính cách này nghiêng về máy móc, có các kế hoạch và ý tưởng rất hợp lý, và họ có thể giữ bình tĩnh và lý trí trong một thời gian dài. Tuy nhiên, tính tự phát luôn ở bên trong họ \n- nó chỉ đơn giản là đang tạm ở "phía sau", tích lũy năng lượng và đang chờ thời điểm thích hợp để bùng phát nó cùng một lúc. Sự bùng phát đó thường làm mọi người xung quanh ngạc nhiên, đặc biệt là những người chưa từng thấy ISTP làm điều gì tương tự trước đây. Những người mang loại tính cách ISTP rất giỏi trong việc kiểm soát năng lượng và giữ chúng để làm những thứ quan trọng khác.',
      'sunghiep3' :'ISTP là những cá nhân rất riêng tư, điều này càng làm cho người khác khó hiểu về họ hơn. Đôi khi các ISTP đột nhiên trở nên bướng bỉnh và lớn tiếng, đặc biệt là khi các nguyên tắc và thói quen của họ đang bị chỉ trích.',
      'sunghiep4' :'Các ISTP cũng khá hài hước, điều này giúp xoa dịu tình hình căng thẳng hay giải quyết một số tình huống khó xử bằng sự hài hước. Nhưng ISTP không phải là người nhạy cảm, họ gặp khó khăn để nhận ra ranh giới của những gì được phép và dự kiến ​​trong những tình huống cảm xúc \n- do đó, họ vô tình có thể làm tổn thương người thuộc loại nhạy cảm hơn.',
      'dacdiem':'- Có khả năng tuyệt vời trong việc áp dụng những suy luận logic và lập luận để giải quyết vấn đề và khám phá ra cách vận hành của mọi hoạt động.\n- Thường nắm vững những lý thuyết và suy nghĩ trừu tượng, nhưng đặc biệt không thích làm việc với chúng trừ khi chúng đem lại những ứng dụng thực tế.\n- Là người mạo hiểm, ưa thích hành động.\n- Có hứng thú trong việc tìm hiểu mọi thứ vận hành như thế nào và tại sao chúng lại như vậy.\n- Luôn thu thập và lưu trữ thông tin từ thế giới bên ngoài.\n- Là những người năng động thích làm việc.',
      'goiynghe':'- Pháp y, Cảnh sát và thám tử,Kỹ sư, Thợ cơ khí, Lập trình viên, chuyên gia phân tích hệ thống, chuyên gia máy tính, Thợ mộc',
    }, 
  ];
  int get getResult{
    int id;
    if (result =="ENFJ") {
      id = 0;
    } else if (result =="ENFP") {
      id = 1;
    } else if (result =="ENTJ") {
      id =2;
    } else if (result =="ENTP") {
      id = 3;
    } else if (result =="ESFJ") {
      id = 4;
    }else if (result =="ESFP") {
      id = 5;
    } else if (result =="ESTJ") {
      id = 6;
    } else if (result =="ESTP") {
      id = 7;
    } else if (result =="INFJ") {
      id = 8;
    } else if (result =="INFP") {
      id = 9;
    } else if (result =="INTJ") {
      id = 10;
    } else if (result =="INTP ") {
      id = 11;
    } else if (result =="ISFJ") {
      id = 12;
    }else if (result =="ISFP ") {
      id = 13;
    } else if (result =="ISTJ") {
      id = 14;
    }else {
      id = 15;
    }
    return id;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        padding:const EdgeInsets.all(8.0),
        child: ListView.builder(
          itemCount: 1,
          itemBuilder: (BuildContext context,_) {  
            return SingleChildScrollView(
              child: Column(
                children: [
                  TextDetail(sunghiep[getResult]['sunghiep1'] as String),
                  const SizedBoxDetail(),
                  TextDetail(sunghiep[getResult]['sunghiep2'] as String),
                  const SizedBoxDetail(), 
                  TextDetail(sunghiep[getResult]['sunghiep3'] as String),
                  const SizedBoxDetail(),       
                  TextDetail(sunghiep[getResult]['sunghiep4'] as String),
                  const SizedBoxDetail(), 
                  Text('Đặc điểm của tính cách $result',style: const TextStyle(fontSize: 16,fontWeight: FontWeight.w900),),
                  TextDetail(sunghiep[getResult]['dacdiem'] as String),
                  const SizedBoxDetail(), 
                  Text('Nghề nghiệp phù hợp với tính cách $result',style: const TextStyle(fontSize: 16,fontWeight: FontWeight.w900),),
                  TextDetail(sunghiep[getResult]['goiynghe'] as String),
                ],
              ));
          },
          
        ),
    );
  }
}