import 'package:flutter/material.dart';
import 'package:fluttter_quiz_app/widgets/sizedbox.dart';
import 'package:fluttter_quiz_app/widgets/text.dart';

class TongQuan extends StatelessWidget {
  TongQuan({ Key? key, required this.result }) : super(key: key);
  final String result;
  
  final tongquan = [
    {
      'tinhcach':'ENFJ',
      'tongquan1' :'Có khoảng 2% dân số mang loại tính cách này, ENFJ là loại tính cách có sức ảnh hưởng rất lớn. Các ENFJ thường rất lôi cuốn và có tài hùng biện, họ dễ dàng truyền đạt ý tưởng, quan điểm của họ với mọi người. ENFJ quan tâm đến mọi người một cách chân thành, những người xung quanh ENFJ thường thấy chúng rất truyền cảm và dễ thương.',
      'tongquan2' :'Các ENFJ là những người có sự quan tâm đặc biệt đến người khác. Họ hiểu được những khả năng của mọi người. Và hơn tất cả các nhóm khác, họ là những người có kĩ năng "đối nhân xử thế" rất xuất sắc. Họ hiểu và quan tâm đến mọi người xung quanh, và có khả năng đặc biệt là mang lại điều tốt đẹp nhất cho người khác. Trao yêu thương, hỗ trợ và dành thời gian cho người họ thích là niềm hứng thú chính của các ENFJ. Họ biết cách lắng nghe, thấu hiểu, giúp đỡ cũng như động viên người khác. ENFJ cảm thấy thích thú và mãn nguyện nhất khi mang lại những giá trị thiết thực cho người khác.',
      'tongquan3' :'Các ENFJ có khả năng đối nhân xử thế phi thường và luôn diễn đạt trôi chảy và rõ ràng những gì họ muốn nên các ENFJ có khả năng khiến người khác làm chính xác những gì họ muốn. Họ "đi guốc trong bụng" người khác và luôn nhận được cách phản ứng mà họ mong muốn. Những động cơ của các ENFJ thường không xuất phát từ sự ích kỉ, nhưng cũng có một số ENFJ chưa phát triển hoàn thiện - được biết đến như là những người đã sử dụng sức mạnh của mình để thao túng người khác.',
      'tongquan4' :'Các ENFJ là những người hướng ngoại, nên dành thời gian để ở một mình sẽ cực kỳ quan trọng đối với họ. Điều đó cũng có thể là vấn đề đối với ENFJ, vì họ có xu hướng tự làm khó mình và trở nên bế tắc khi ở một mình. Vì vậy, ENFJ cần phải tránh tách biệt bản thân và nên hòa nhập với người khác trong các hoạt động thường ngày hơn. Các ENFJ thường định hướng cuộc sống và các ưu tiên của họ theo nhu cầu của người khác mà không nhận ra được những gì họ mong muốn. Việc đặt lợi ích của người khác lên trên lợi ích bản thân là điều tự nhiên với tính cách của ENFJ, nhưng họ cần phải dành thời gian để suy nghĩ và hiểu rõ nhu cầu của mình để chăm lo cho bản thân nhiều hơn.',
      'tongquan5' :'Các ENFJ thường dè dặt hơn về việc biểu lộ bản thân so với những loại tính cách hướng ngoại khác. Mặc dù có những niềm tin rất mạnh mẽ nhưng họ thường tự kiềm chế việc bộc lộ những niềm tin đó nếu chúng cản trở họ trong việc đem lại điều tốt đẹp nhất cho người khác. Bởi vì sự quan tâm lớn nhất của ENFJ là trở thành một người trung gian giúp thay đổi người khác, nên họ thường thay đổi để tương tác cho phù hợp với mỗi người. Giống như thích nghi của tắc kè, họ thay đổi để phù hợp với hoàn cảnh, hơn là cho cá nhân họ.',
    },
    {
      'tinhcach':'ENFP',
      'tongquan1':'Có khoảng 7% dân số mang loại tính cách này. Những người mang tính cách ENFP thường rất tò mò, hiếu kỳ, duy tâm và khá bí ẩn. Họ tìm kiếm ý nghĩa và rất quan tâm đến động cơ của người khác, họ thấy cuộc sống thật rộng lớn, nhiều câu đố phức tạp ở những nơi mà mọi thứ được kết nối. Các ENFP có xu hướng nhận thức cá nhân và khả năng thấu hiểu cảm xúc người khác cao - Điều này, cộng với sự đam mê và kỹ năng xã hội của họ, thường làm cho họ rất được nhiều người ngưỡng mộ và có sức ảnh hưởng cao.',
      'tongquan2':'Tính cách đặc trưng của các ENFP là sự nhiệt tình, đặc biệt là khi nói đến những điều mà châm ngòi cho trí tưởng tượng của họ - trong trường hợp này, các ENFP có thể rất năng động và có sức thuyết phục, có thể dễ dàng thuyết phục người khác gia nhập với họ. Trớ trêu thay, đặc điểm này cũng có thể quay lưng lại với các ENFP, khi họ đột nhiên thấy mình ở trung tâm của sân khấu, được coi là nhà lãnh đạo truyền cảm hứng và những bậc thầy của người khác, các ENFP phấn đấu để được độc lập, vì vậy không ngạc nhiên, không phải lúc nào họ cũng mong muốn trở thành tâm điểm của sự chú ý.',
      'tongquan3':'Những người có các loại tính cách ENFP biết làm thế nào để thư giãn, dựa trên kỹ năng tưởng tượng, nhiệt tình và kỹ năng sống của họ - Ví dụ, họ có thể rất nghiêm túc và đam mê công việc trong ngày và sau đó cho xả hơi trong một bữa tiệc hoang dã trong một hộp đêm. Sự chuyển đổi giữa hai trạng thái đó có thể tức thời, thường ngạc nhiên ngay cả với người bạn thân nhất.',
      'tongquan4':'Các ENFP rất tình cảm và nhạy cảm, họ xem cảm xúc như một cái gì đó mà tất cả mọi người nên dành thời gian để hiểu và thể hiện. Tuy nhiên, đặc điểm này cũng có thể gây ra rất nhiều căng thẳng cho họ, như ENFP thường có thể tập trung quá nhiều vào động cơ của người khác và ý nghĩa của hành động đó. Quan sát và trực quan là 2 cá tính nổi trội của họ, nhưng họ có thể có những sai sót nghiêm trọng khi cố gắng sử dụng những suy luận từ cảm xúc của người khác làm cơ sở cho quyết định của mình.',
      'tongquan5':'Tóm lại, các ENFP không phải là người tuân thủ, phục tùng, họ đi theo con đường riêng của mình và tin vào trực giác của họ. Họ có nhiều tài năng, nhưng họ chỉ thể hiện khi có đủ tự do. Những người mang tính cách này có thể trở nên thiếu kiên nhẫn và thất vọng nếu họ bị đặt vào vị trí nhàm chán, không thể tự do thể hiện bản thân - nhưng khi ENFP tìm thấy vị trí, công việc mà họ mong muốn thì trí tưởng tượng, sự đồng cảm và lòng can đảm của họ có thể tạo ra kết quả đáng kinh ngạc.',
    },
    {
      'tinhcach':'ENFJ',
      'tongquan1':'Có khoảng 3% dân số mang tính cách này, ENTJ có cá tính rất lôi cuốn, lý trí và nhạy bén. Họ rất giỏi lãnh đạo và truyền cảm hứng cho người khác. ENTJ là loại tính cách có khả năng lãnh đạo tốt nhất trong các loại tính cách. Theo ENTJ thì "Không có gì là không thể nếu bạn quyết tâm". Đương nhiên, các ENTJ hiếm khi gặp khó khăn khi thuyết phục người khác rằng mục tiêu lựa chọn bởi ENTJ cũng nên trở thành một trong những mục tiêu cá nhân của họ.',
      'tongquan2':'Các ENTJ là những người lãnh đạo bẩm sinh. Thế giới của họ luôn tràn ngập những tiềm năng, nó bày ra trước mắt họ đủ loại thử thách để chinh phục, họ rất muốn trở thành người chinh phục các thử thách đó. Họ có xu hướng làm nhà lãnh đạo, vì họ nắm bắt rất nhanh các vấn đề phức tạp, có khả năng tiếp thu một lượng lớn những thông tin khách quan, và cuối cùng là sự nhạy bén và tính quyết đoán khi đưa ra quyết định. ENTJ là những người luôn "chịu trách nhiệm".',
      'tongquan3':'Các ENTJ có rất nhiều tài năng vì vậy quyền lực cá nhân của họ rất lớn. ENTJ là những nhà tư duy sáng tạo, quyết đoán và có tầm nhìn xa với một khả năng tuyệt vời trong việc biến những lý thuyết và tiềm năng trở thành những kế hoạch hành động cụ thể và rõ ràng. Họ có cá tính nổi trội mạnh mẽ, và có đủ mọi công cụ để đạt được bất cứ mục tiêu nào mà họ đặt ra.',
      'tongquan4':'Trong thế giới của ENTJ không có chỗ cho sai lầm. Họ không thích nhìn thấy những sai sót, đặc biệt là những sai sót bị lập lại, và họ không thể chịu đựng nổi sự kém cỏi, thiếu khả năng. ENTJ có thể trở nên rất cáu gắt khi lòng kiên nhẫn của họ bị thử thách trong những trường hợp trên, vì họ vốn dĩ khó cảm thông với cảm xúc của người khác, và hơn thế nữa họ tin rằng họ chẳng việc gì phải thay đổi các phán xét của mình để thích ứng với cảm xúc của người khác. Các ENTJ, cũng giống như các kiểu tính cách khác, gặp khó khăn khi nhìn nhận sự việc dưới những quan điểm khác với của mình. Tuy nhiên, các ENTJ không giống như những kiểu tính cách khác là họ không có đủ kiên nhẫn cho những người không cùng quan điểm với họ.',
      'tongquan5':'Các ENTJ cần phải học cách lắng nghe và thừa nhận ý kiến của mọi người, cũng như giá trị của việc thấu hiểu cảm giác của họ. Một khi vẫn chưa nhận thức được các vấn đề này, các ENTJ có thể trở nên độc đoán, đáng sợ và hống hách. Đây là một vấn đề lớn đối với các ENTJ mỗi khi họ cảm thấy thiếu thốn những thông tin quan trọng và sự hợp tác từ người khác. Trong cuộc sống riêng tư của ENTJ, điều này có thể khiến cho họ trở nên độc đoán trong vai trò vợ/chồng hoặc cha/mẹ.',
    },
    {
      'tinhcach':'ENTP',
      'tongquan1':'Có khoảng 3% dân số mang loại tính cách này, các ENTP rất thích tranh luận, họ không quan tâm đang tranh luận về cái gì, miễn là nó thú vị. Họ có thể không thực sự ủng hộ ý tưởng họ đang tranh cãi, nhưng có thể quyết định đi ngược lại quan điểm hiện hành, họ xem điều này như là một bài tập tinh thần. Các ENTP rất nhanh trí và độc đáo, mang đến cho họ một lợi thế lớn trong cuộc tranh luận, học thuật và chính trị - tuy nhiên, họ cũng có xu hướng làm rất tốt trong nhiều lĩnh vực khác đòi hỏi phải sẵn sàng để thách thức những ý tưởng hiện có và sắp xếp nhiều luận cứ.',
      'tongquan2':'Một trong những lý do tại sao các ENTP có thể giữ lý lẽ của họ trong gần như mọi cuộc tranh luận là kiến thức và khả năng nhanh chóng nghĩ ra ý tưởng khác của họ, tạo các kết nối độc đáo trong tranh luận. Họ làm điều này với tốc độ rất nhanh và không cần nhiều sức lực - Sự tấn công của lập luận đến từ các ENTP dễ gây bối rối cho đối thủ của họ. Điều này có thể là tốt hoặc xấu, tùy thuộc vào ENTP đang tranh cãi với ai - họ có thể dễ dàng xóa sạch lý lẽ của đối thủ trong một cuộc tranh luận về chính trị, nhưng gây ra căng thẳng to lớn trong một mối quan hệ tình cảm nếu họ cố gắng làm điều đó với đối tác của họ .',
      'tongquan3':'Các ENTP cần phải cẩn thận để giữ cho sở thích tranh luận nằm trong vòng kiểm soát, như sự tiến triển thực tế thường quan trọng hơn sự thật. Những người có loại tính cách này biết rất rõ điều này, nhưng họ cũng cần phải hiểu rằng những gì họ xem như thú vui có thể gây tổn thương cho người khác.',
      'tongquan4':'Các ENTP có xu hướng sử dụng sự thông minh của mình một cách rất cụ thể và điều này đặc biệt đáng chú ý trong môi trường chuyên nghiệp - họ thích động não và phác thảo tất cả các lựa chọn, nhưng họ cố tránh tham gia vào việc triển khai thực tế. Một lần nữa, một đặc điểm như vậy có thể rất có giá trị trong các tình huống nhất định, nhưng gây ra căng thẳng tại nơi làm việc, ENTP có thể được xem là người có nhiều ý tưởng, nhưng không sẵn sàng làm việc chăm chỉ để thực hiện ý tưởng của họ. ENTP cũng có xu hướng không tuân thủ, thích thách thức quy định hiện hành và các thủ tục, những điều này không thể thay đổi họ, họ muốn xóa bỏ mô hình hiện tại và lên mô hình mới.',
      'tongquan5':'Các ENTP thường thích làm việc với những ý tưởng phức tạp và các thử thách khó khăn. Họ thích những suy nghĩ lớn và làm tốt nó - để có được cá tính này có thể mất một thời gian dài cho một ENTP, khi đó tính cách mạnh mẽ này sẽ được phát huy và một khi họ làm, những dòng ý tưởng sẽ không ngừng tuôn ra. Tuy nhiên, ENTP vẫn sẽ cần phải dựa vào người khác để sắp xếp, triển khai.',
    },
    {
      'tinhcach':'ESFJ',
      'tongquan1':'3 tính cách đặc trưng của ESFJ là: Thực tế, vị tha và hòa đồng. Có khoảng 12% dân số mang tính cách này. Các ESFJ muốn được phục vụ người khác và họ rất nghiêm túc khi đưa ra các cam kết. Các ESFJ rất giỏi làm việc nhóm, họ luôn cảm nhận được sự căng thẳng và không hòa hợp. Họ rất truyền thống, làm hết sức mình để hỗ trợ và bảo vệ quyền và pháp luật. Những người có loại cá tính này cũng có xu hướng rất tận tâm, cho dù họ đang đóng vai trò chủ của buổi tiệc hay một nhân viên xã hội. Khá dễ dàng để nhận ra ESFJ trong các sự kiện xã hội - họ sẽ sắp xếp đủ thời gian để trò chuyện với tất cả mọi người.',
      'tongquan2':'Các ESFJ luôn luôn cố gắng tìm kiếm sự hài hòa trong mọi lĩnh vực có thể, họ dễ bị xúc phạm bởi vì sự không quan tâm hoặc miễn cưỡng của người khác để tham gia vào các hoạt động mà ESFJ thấy cao quý và quan trọng. Nếu không kiểm soát được, điều này có thể là một trong những điểm yếu ESFJ và những người có loại cá tính này nên cố gắng ý thức về hành vi của mình xung quanh những người khác văn hóa, kiến thức hay khác tính cách.',
      'tongquan3':'Các ESFJ rất quan tâm đến hình thức bên ngoài và rất nhạy cảm về địa vị xã hội của họ - Chủ để cá nhân này thực sự là một "bãi mìn" cho những ai quyết định thảo luận với một ESFJ, đặc biệt là có một vài chỉ trích hay chế nhạo liên quan. Các ESFJ cũng tôn trọng hệ thống phân cấp và làm hết sức mình để đạt được một vị trí trong chính quyền.',
      'tongquan4':'Tính cách của các ESFJ là thích được tham gia vào các cuộc trò chuyện tập trung vào chủ đề thực tế hoặc cuộc sống của người khác - tuy nhiên, họ sẽ cố gắng để thoát ra khỏi các cuộc thảo luận một khi nó chạm vào vấn đề trừu tượng hay lý thuyết. Các ESFJ không quan tâm đến các vấn đề phân tích những ý tưởng phức tạp hay các thảo luận về nguyên nhân và hậu quả, đây là một sự tương phản hoàn toàn với các loại tính cách NT.',
      'tongquan5':'Các ESFJ có xu hướng rất nồng nhiệt, nhạy cảm và sâu sắc. Đây là những đặc điểm tuyệt vời, nhưng nó cũng có thể gây khó khăn cho họ và những người xung quanh - những người có loại cá tính này có khả năng gặp khó khăn để đối phó với các tình huống có liên quan đến những lời chỉ trích hoặc xung đột.',
    },
    {
      'tinhcach':'ESFP',
      'tongquan1':'Đối với ESFP - "cuộc sống là một bữa tiệc không bao giờ kết thúc". Có khoảng 7.5% dân số mang tính cách này, Các ESFP thích được ở trung tâm của sự chú ý và họ cũng thích cả những điều đơn giản nhất - Sự vui vẻ và bản chất bốc đồng của họ thường rất hấp dẫn những người khác. Những người có loại cá tính này không bao giờ hết những ý tưởng và sự tò mò của họ là không giới hạn - họ sẽ luôn luôn là một trong những người đầu tiên thử một cái gì đó mới và hấp dẫn.',
      'tongquan2':'Các ESFP yêu thích giao tiếp với người khác và họ có thể bỏ ra hàng giờ để trò chuyện về nhiều chủ đề khác nhau. Không có dấu hiệu nào chỉ rõ hơn một người thuộc loại ESFP là việc người đó bỏ cả tiếng đồng hồ nói về tất cả mọi thứ khác trừ cái chủ đề được coi là lý do chính cho cuộc nói chuyện. Tính cách này này có xu hướng rất phổ biến trong loại hướng ngoại.',
      'tongquan3':'Những người mang tính cách ESFP thường sống trong thế giới của những cơ hội và tận hưởng những niềm vui. Họ được đắm mình trong một buổi biểu diễn không bao giờ kết thúc, cố gắng để cổ vũ người khác lên. Các ESFP vô cùng tài năng khi làm cho người khác cảm thấy tốt và vui mừng, và họ vô cùng thích điều này. Sự dí dỏm trần tục và thường độc đáo của ESFP là một biểu tượng hoàn hảo của tính khôi hài của họ.',
      'tongquan4':'Các ESFP có một cảm giác thẩm mỹ phát triển cao và điều này là một trong những đặc điểm tính cách mạnh nhất của họ. Đây là loại người sẽ thích thú trang trí môi trường xung quanh và nhận ra giá trị chất lượng trong nhiều thứ khác.',
      'tongquan5':'Các ESFP rất tinh ý, có thể nhận thấy và đáp ứng trạng thái cảm xúc đau khổ của người khác. Lập kế hoạch và tư duy dài hạn thường là đặc điểm tính cách yếu nhất của họ, họ là những nhà chiến lược và quy hoạch kém, nhưng họ có khả năng rất tốt để cung cấp lời khuyên thực tế và hỗ trợ tinh thần.',
    },
    {
      'tinhcach':'ESTJ',
      'tongquan1':'Ba đặc trưng trong tính cách của các ESTJ là: nguyên tắc, truyền thống và ổn định. Có khoảng 11,5% dân số mang tính cách này, những người mang loại tính cách ESTJ cảm thấy cần phải gắn kết với một điều gì đó - nó có thể là một gia đình, một cộng đồng hay một số nhóm xã hội khác. Họ thích "việc tổ chức" của người khác và đảm bảo rằng họ sẽ tuân thủ các quy tắc truyền thống hoặc đưa ra bởi những người có thẩm quyền.',
      'tongquan2':'Với tính cách hướng ngoại, các ESTJ thích kết nối với những người khác và đóng vai trò tích cực trong các tổ chức truyền thống. Hạnh phúc gia đình rất quan trọng với các ESTJ và họ làm hết sức mình để nuôi dưỡng và bảo vệ gia đình.',
      'tongquan3':'Các ESTJ rất tận tâm và có trách nhiệm. Họ sẽ làm mọi thứ có thể để hoàn thành nhiệm vụ của mình và đáp ứng lời hứa của họ. Những người có tính cách này rất tôn trọng và thúc đẩy đạo đức nghề nghiệp, và ghét cay ghét đắng gian lận hoặc bất kỳ nỗ lực để "cắt góc", đặc biệt là tại nơi làm việc. Họ cũng rất muốn tranh giành các vị trí quyền lực.',
      'tongquan4':'Các ESTJ thường có ý chí mạnh mẽ và không sợ lên tiếng và bảo vệ ý kiến ​​của mình, ngay cả khi họ đang phải đối mặt với một đối thủ đáng gờm. Ví dụ, một trong những cấp dưới của họ là không đủ năng lực hoặc đơn giản là lười biếng, các ESTJ sẽ không ngần ngại thể hiện sự phẫn nộ của họ. Tính cách của các ESTJ là sẽ bám các nguyên tắc của họ, ngay cả khi tất cả mọi người quay lưng với họ.',
      'tongquan5':'Mang đặc điểm S , Các ESTJ sống trong thế giới của sự thật rõ ràng và có thể kiểm chứng. Họ là trung thực và thẳng thắn, sống trong hiện tại và ghi nhớ tất cả những gì đang xảy ra xung quanh họ. Họ có một tầm nhìn rõ ràng và sự hiểu biết về những gì là chấp nhận được và những gì không thể được - điều này thường làm cho ESTJ trở thành lãnh đạo hay cán bộ quản lý xuất sắc, mặc dù cấp dưới đôi khi có thể phàn nàn về tính cứng nhắc của họ. ESTJ cảm thấy khá dễ dàng để phát triển và cải tiến các kế hoạch hành động khác nhau - họ có thể làm cho những dự án phức tạp nhất trở nên đơn giản giống như việc "đi bộ trong công viên".',
    },
    {
      'tinhcach':'ESTP',
      'tongquan1':'Có khoảng 4% dân số mang tính cách này, những người có các loại tính cách ESTP rất tập thể, tự phát và thẳng thắn. Đôi khi họ bị xem là thô lỗ hoặc thiếu thận trọng, nhưng thực sự các ESTP yêu thích hành động và luôn luôn nhảy ngay vào trung tâm của "cơn bão". Các ESTP không thích các cuộc tranh luận lý thuyết hoặc suy nghĩ về tương lai - họ chỉ quan tâm đến thời điểm hiện tại và tập trung tất cả nỗ lực của họ vào những thứ họ thích hơn là những suy nghĩ về những gì có thể.',
      'tongquan2':'Các ESTP thường ít khi lên kế hoạch hành động chi tiết, họ thường nhanh chóng lao vào công việc, họ tìm ra các sai sót và hành động ngay lập tức. Nếu cần thiết, họ không ngại quay lại và sửa chữa sai lầm của mình. Những người có loại tính cách này cũng có một khả năng bẩm sinh để nhận biết những suy nghĩ và động cơ của người khác, các ESTP có thể dễ dàng phát hiện những thay đổi nhỏ trong biểu hiện của một ai đó trên khuôn mặt, quần áo, hành vi,... Các loại tính cách khác không có khả năng bí ẩn này.',
      'tongquan3':'Những người mang tính cách ESTP cũng có xu hướng xem luật lệ, quy tắc và nghĩa vụ như là các khuyến cáo hoặc hướng dẫn chứ không phải là nguyên tắc cứng nhắc. Nếu ESTP tin rằng một cái gì đó phải được thực hiện và nguyên nhân chính là sự đúng đắng và xứng đáng, họ sẽ đi trước và làm điều đó, bất chấp những gì pháp luật hoặc quy tắc xã hội cảnh báo. Điều này không có nghĩa là để nói rằng ESTP là những người phạm pháp - họ thường có một sự hiểu biết rõ ràng về thiện và ác - đúng hơn, họ có xu hướng đưa giá trị cá nhân, ý kiến và nguyên tắc trên những gì người khác hay xã hội suy nghĩ.',
      'tongquan4':'Các ESTP rất thích xem phim, theo đuổi niềm đam mê và những thú vui vật chất khác. Tuy nhiên, những người có loại tính cách này nên biết rằng niềm đam mê của họ có thể thực hiện bằng nhiều cách khác nhau, trong đó có khá nhiều trò nguy hiểm hoặc không lành mạnh - ví dụ như cờ bạc, có nhiều con bạc là ESTP. Đặc điểm tính cách của ESTP cũng có thể khiến họ vô tình làm tổn thương người khác - ESTP rất thẳng thắn và dựa trên sự kiện và logic (đặc điểm T ) chứ không phải là cảm xúc (đặc điểm F), nên lời nói của họ có thể dễ dàng gây tổn thương những người mang loại tính cách nhạy cảm hơn.',
      'tongquan5':'Các ESTP không thích lý thuyết và tư duy trừu tượng, họ thường gặp khó khăn trong trường học, đặc biệt là trong những năm sau đó. Những người có loại tính cách này xem các cuộc thảo luận lý thuyết là nhàm chán và vô nghĩa. Ngược lại, năng lượng và niềm đam mê của họ hầu như không giới hạn khi nói đến các lĩnh vực mà họ cho là thực tế và thú vị. Các ESTP có thể rất truyền cảm và có sức thuyết phục - điều này làm cho họ trở nên xuất sắc với vị trí đại diện bán hàng, tư vấn và các doanh nhân. Loại tính cách này thực sự là rất nhiều tài năng - điều quan trọng là mỗi ESTP nhận ra tài năng, cũng như những điểm mạnh và điểm yếu của mình.',
    },
     {
      'tinhcach':'INFJ',
      'tongquan1':'Có rất ít người mang tính cách này, chỉ chiếm khoảng 1% dân số và họ mang trong mình khá nhiều đặc điểm bất thường. Mặc dù sự hiện diện của họ có thể được miêu tả như là rất yên tĩnh, nhưng các INFJ lại thường có nhiều ý kiến ​​mạnh mẽ, đặc biệt là khi nói đến các vấn đề mà họ cho là thực sự quan trọng trong cuộc sống. Nếu một INFJ chiến đấu cho một điều gì đó thì nguyên nhân chính là vì họ tin vào ý tưởng riêng của mình, không phải vì một số lý do ích kỷ.',
      'tongquan2':'Tính cách của INFJ là hướng đến việc giúp đỡ những người đang cần - họ có thể vội vàng đến nơi một thảm họa lớn, tham gia vào nỗ lực cứu hộ, làm công việc từ thiện, ... Các INFJ coi đây là nhiệm vụ và mục đích của họ trong cuộc sống - những người có loại cá tính này vững tin rằng cách tốt nhất để giúp thế giới là loại bỏ tất cả các kẻ bạo ngược. Nghiệp chướng và các khái niệm tương tự là rất hấp dẫn đối với INFJ.',
      'tongquan3':'Những xu hướng đó cũng được củng cố bởi thực tế rằng tính cách của INFJ có một sự kết hợp độc đáo của chủ nghĩa lý tưởng và quyết đoán - điều này có nghĩa rằng sự sáng tạo và trí tưởng tượng của họ có thể được dẫn thẳng tới một mục tiêu cụ thể. Vài loại tính cách khác cũng có đặc điểm này và đây là một trong những lý do quan trọng nhất lý giải tại sao nhiều INFJ thực hiện ước mơ của họ và thực hiện một cách cương quyết lâu dài.',
      'tongquan4':'Các INFJ nên cẩn thận để tránh "quá nhiệt" như nhiệt huyết và quyết tâm của họ đôi khi có thể vượt quá tầm kiểm soát. Mang đặc điểm hướng nội, thỉnh thoảng các INFJ cần phải có khoảng "thời gian một mình" để tĩnh dưỡng nếu không năng lượng tích trữ trong họ sẽ cạn kiệt rất nhanh. Nếu điều này xảy ra, các INFJ có thể làm mọi người ngạc nhiên bằng cách rút khỏi tất cả các hoạt động của họ trong một thời gian - và kể từ đó mọi người thường thấy các INFJ dường như hướng ngoại, điều này có thể làm cả hai ngạc nhiên và lo âu.',
      'tongquan5':'Các INFJ hết sức quan tâm đến cảm xúc của người khác và mong đợi họ trả ơn. Đương nhiên những người có loại tính cách này rất nhạy cảm và dễ bị tổn thương vì những xung đột - thậm chí các INFJ có lý trí nhất cũng gặp khó khăn để tránh bị chỉ trích cá nhân. Đây là điểm yếu của INFJ - nếu một người nào đó mang tính cách INFJ không thể thoát khỏi cuộc xung đột, họ sẽ làm hết sức mình để đối phó với nó, nhưng điều này sẽ gây ra nhiều căng thẳng và cũng có thể có thể dẫn đến vấn đề sức khỏe hoặc hành vi rất phi lý.',
    },
    {
      'tinhcach':'INFP',
      'tongquan1':'Có khoảng 4,5% dân số mang tính cách này, các INFP thường được coi là điềm tĩnh, kín đáo hoặc thậm chí nhút nhát. Tuy nhiên, đừng để vẻ bề ngoài đánh lừa. Dù các INFP có thể hơi thận trọng, nhưng không thể xem thường ngọn lửa và sự đam mê bên trong họ. Những người có loại tính cách này là thực sự rất trìu mến, một đặc điểm không thường thấy ở các loại tính cách khác. Lòng trắc ẩn của họ thực sự nồng nhiệt và lâu dài - nhưng các INFP sẽ sử dụng nó khá dè dặt, họ hướng nguồn năng lượng này đến với một vài người được chọn hoặc một nguyên nhân xứng đáng. Chủ nghĩa lý tưởng là ngọn cờ của những người mang tính cách INFP - và họ rất tự hào về nó. Thật không may, nó cũng khiến cho các INFP thường có thể cảm thấy bị hiểu lầm và bị cô lập, vì rất ít người mang chủ nghĩ lý tưởng như họ.',
      'tongquan2':'Các INFP tìm kiếm sự hài hòa trong cuộc sống của họ và môi trường xung quanh, thường cảm thấy thất vọng vì tất cả những điều xấu xảy ra trên thế giới và cố gắng để tạo ra một cái gì đó tích cực. Những người có loại tính cách này có xu hướng nhìn sự vật và hành động từ quan điểm duy tâm, chứ không phải là từ tư duy logic. Họ đáp ứng với vẻ đẹp, đạo đức, đức hạnh chứ không phải là tiện ích, hiệu quả hoặc giá trị.',
      'tongquan3':'Các INFP thường nói những câu ẩn dụ và ngụ ngôn. Họ cũng có khả năng tuyệt vời trong việc sáng tạo ra các biểu tượng hay giải thích cách biểu tượng. Vì lý do này, các INFP có khả năng viết bẩm sinh và thích thơ. Loại tính cách này không sùng bái tư duy logic, không giống như các loại NT - theo quan điểm của họ, logic không phải là luôn luôn cần thiết. Các INFP sẽ thích thú thảo luận với giả thuyết hay triết học nhiều hơn bất kỳ loại nào khác.',
      'tongquan4':'Các INFP có đặc điểm chung với các loại NF - họ năng khiếu về ngoại ngữ là rất đặc biệt. Các INFP cũng thường trở thành nhà văn lớn hay các diễn viên giỏi, vì họ có thể dễ dàng phản ánh và truyền tải ý tưởng của mình bằng cách sử dụng nhân vật hư cấu. Nói chung, những người có loại tính cách này là cực kỳ sáng tạo, đổi mới và định hướng được mục tiêu - họ có thể là những người ủng hộ tuyệt vời cho những nguyên nhân họ thực sự tin tưởng.',
      'tongquan5':'Cuối cùng, hầu hết các INFP có khả năng nhận thấy những gợi ý tốt (dù là rất nhỏ) ở những người khác. Trong mắt của INFP, ngay cả những người ghê tởm nhất cũng sẽ có một cái gì đó xứng đáng với sự tôn trọng hoặc, ít nhất là sự cảm thông.',
    },
    {
      'tinhcach':'INTJ',
      'tongquan1':'INTJ là một trong những loại tính cách hiếm nhất và thú vị nhất - chỉ chiếm khoảng 2% dân số Hoa Kỳ (INTJ nữ là đặc biệt hiếm - chỉ 0,8%), Các INTJ thường được xem là rất thông minh và bí ẩn một cách khó hiểu. Những người mang tính cách INTJ thường tỏa ra sự tự tin, dựa trên kho lưu trữ khổng lồ của họ về kiến thức bao trùm nhiều lĩnh vực và phạm vi khác nhau. Các INTJ thường bắt đầu phát triển những kiến ​​thức trong thời thơ ấu (những "con mọt sách" là biệt danh khá nổi tiếng của INTJ) và tiếp tục làm điều đó sau này trong cuộc sống.',
      'tongquan2':'Khi một người mang tính cách INTJ nắm vững kiến thức ở lĩnh vực mà họ đã chọn (INTJ có thể tìm thấy thế mạnh của họ trong một số lĩnh vực), họ có thể nói một cách thẳng thắn và trung thực rằng họ có biết hay không câu trả lời cho một câu hỏi cụ thể nào đó. Các INTJ biết những gì họ biết và quan trọng hơn - họ rất tự tin vào kiến thức đó. Không ngạc nhiên, loại tính cách này có thể được "dán nhãn" là độc lập nhất trong tất cả các loại tính cách.',
      'tongquan3':'Các INTJ rất quyết đoán, độc đáo và sâu sắc - những đặc điểm này khiến người khác chấp nhận ý tưởng của INTJ chỉ đơn giản vì lý do sức mạnh ý chí tuyệt đối và sự tự tin của họ. Tuy nhiên, các INTJ không tìm kiếm cũng không thích sự chú ý và họ thường giữ ý kiến ​​của mình trong lòng nếu chủ đề của cuộc thảo luận không làm họ quan tâm nhiều.',
      'tongquan4':'Tính cách của các INTJ là rất cầu toàn và họ rất thích cải tiến ý tưởng và các hệ thống mà họ tiếp xúc. Bản tính của các INTJ là tò mò tự nhiên, điều này có xu hướng xảy ra khá thường xuyên. Tuy nhiên họ luôn cố gắng đễ giữ mọi thứ trong tầm kiểm soát, mục tiêu cuối cùng là mỗi ý tưởng được tạo ra bởi tâm trí của INTJ hoặc đến từ bên ngoài cần phải vượt qua các "bộ lọc máu lạnh" được gọi là "Đây có phải việc nên làm?". Đây là cơ chế ứng phó của INTJ và họ đang nổi tiếng trong việc áp dụng nó mọi lúc, đặt câu hỏi tất cả mọi thứ và tất cả mọi người.',
      'tongquan5':'Nói chung, các INTJ thường thích làm việc trong các lĩnh vực mà họ biết rất rõ. Sự nghiệp điển hình của họ là liên quan đến khoa học hay kỹ thuật, nhưng chúng có thể được tìm thấy ở bất cứ đâu, nơi có một nhu cầu của trí thông minh, tâm trí không ngừng nghỉ và cái nhìn sâu sắc (pháp luật, điều tra, một số lĩnh vực chuyên ngành). Các INTJ hiếm khi tìm kiếm vị trí quản lý - nếu họ làm quản lý, bởi vì họ cần thêm sức mạnh và tự do hành động, không phải vì họ thích quản lý con người.',
    },
    {
      'tinhcach':'INTP',
      'tongquan1':'"Triết gia", "kiến trúc sư", "giáo sư trừu tượng",... là những từ ngữ thường được dùng để mô tả loại tính cách INTP. Có khoảng 3% dân số mang tính cách INTP. Các INTP yêu thích lý thuyết và tin rằng tất cả mọi thứ đều có thể phân tích và cải tiến. Họ không quan tâm đến thế giới thực và những thứ thực dụng khác - theo quan điểm của INTP thì nó kém sôi động hơn so với những ý tưởng hay theo đuổi tri thức. Những người có loại tính cách này không có khó khăn để nhận thấy các mô hình mà người khác không thể thấy - điều này làm cho họ trở thành nhà lý thuyết và nhà phân tích xuất sắc.',
      'tongquan2':'Kiến thức được tích lũy là tài sản có giá trị nhất của bất kỳ INTP. Hãy tưởng tượng một bộ máy phức tạp không ngừng hấp thụ, xử lý và tạo ra tất cả các loại lý thuyết - đây là cách mà tâm trí INTP hoạt động. Những người mang tính cách này có tư duy logic chính xác nhất trong tất cả các nhóm tính cách - họ dễ dàng nhận thấy ngay cả những điểm khác biệt nhỏ nhất giữa hai báo cáo hay phát biểu(tuyên bố), cho dù thời gian xảy ra giữa hai lần báo cáo đó là khá lâu. Thật tồi tệ khi nói dối với một INTP, họ sẽ nhận ra ngay. Đôi khi họ có thể mơ mộng, nhưng điều này không phải là vì tâm trí của họ được nghỉ ngơi mà hoàn toàn ngược lại.',
      'tongquan3':'Các INTP rất nhiệt tình và vô tư khi nói đến việc giải quyết các vấn đề - họ khai thác qua các chi tiết và sau đó phát triển một cách tiếp cận độc đáo và cuối cùng là một giải pháp khả thi. Các INTP thường là những người rất thông minh và đầy nhận thức, họ vẫn có thể thiên vị trong một vài tình huống. Họ hoàn toàn thích những ý tưởng và lý thuyết mới và sẽ không bao giờ bỏ lỡ một cơ hội để thảo luận nó với người khác - tuy nhiên, quá trình tư duy không ngừng này cũng làm cho họ trông khá trầm ngâm và tách biệt, cũng như việc tưởng tượng ra một cuộc tranh luận ngay trong tâm trí họ.',
      'tongquan4':'Những người mang tính cách INTP rất thông minh và thậm chí lập dị. Những đặc điểm này, kết hợp với năng lực sáng tạo và suy nghĩ độc đáo, tạo nên một hỗn hợp rất mạnh mẽ. Không ngạc nhiên khi các INTP có nhiều phát minh trong khoa học. INTP không quan tâm nhiều về những dự tính của xã hội và những mục tiêu "bình thường" khác như công việc an toàn - tuy nhiên, họ sẽ làm hết sức mình để tìm một môi trường mà tài năng sáng tạo và tiềm năng của họ có thể được thể hiện.',
      'tongquan5':'Một trong số điểm yếu của INTP là luôn luôn lo sự thất bại, không có loại tính cách nào lo xa đến như vậy. Không tự tin như những người anh em INTJ hay ENTJ, các INTP luôn nghi ngờ về hành động của họ. Ngay cả khi INTP đang tranh luận với ai đó, nhiều khả năng họ cũng đang tranh luận với chính bản thân mình.',
    },
    {
      'tinhcach':'ISFJ',
      'tongquan1':'Trong tất cả các loại tính cách thì ISFJ là loại tính cách có lòng vị tha nhất. Có khoảng 12.5% dân số trên thế giới mang loại tính cách này. Nhiều ISFJ tìm kiếm sự nghiệp trong lĩnh vực học thuật, y học, công tác xã hội hoặc tư vấn; đặc điểm tính cách của họ cũng tỏa sáng trong vai trò hành chính - văn phòng, hoặc thậm chí trong các lĩnh vực có phần bất ngờ như thiết kế nội thất.',
      'tongquan2':'Các ISFJ luôn sống trong một thế giới ấm áp và đầy tình cảm. Họ rất nồng ấm và nhân hậu, luôn tin vào những điều tốt đẹp nhất của người khác. Họ tôn trọng sự hòa hợp và hợp tác, họ cũng rất nhạy cảm với cảm giác của con người. ISFJ được xem là những người rất ân cần và luôn quan tâm đến mọi người. Khả năng khai thác những điều tốt nhất của người khác xuất phát từ niềm tin vững chắc vào những điều tốt đẹp nhất.',
      'tongquan3':'ISFJ có những ý tưởng rõ ràng trong việc hình dung sự việc sẽ như thế nào, và họ nỗ lực để đạt được nó. Họ thường trân trọng lòng nhân hậu và sự an toàn, tuân thủ luật pháp và tôn trọng phong tục tập quán. Họ tin vào những phương thức có sẵn bởi vì chúng luôn hoạt động hiệu quả, vì vậy họ không bao giờ áp dụng phương thức mới khi làm việc, trừ khi họ được giới thiệu một phương thức mới với lời giải thích rõ ràng tại sao nó tốt hơn phương pháp đã có.',
      'tongquan4':'ISFJ là người luôn đề cao trách nhiệm và nghĩa vụ của mình. Họ chịu trách nhiệm một cách nghiêm túc và tạo được sự tin tưởng vậy nên mọi người hay nhờ cậy họ. Khi được nhờ cậy họ rất ít khi từ chối và điều này có thể sẽ trở thành gánh nặng với họ. Vì ISFJ luôn đặt nhu cầu của người khác lên trên nhu cầu bản thân nên khi giúp đỡ ai đó họ không muốn người đó biết họ đang gặp khó khăn. ISFJ cần học cách nhận thức, đánh giá và thể hiện nhu cầu của bản thân nếu như không muốn trở thành người quá bận rộn vì việc của người khác.',
      'tongquan5':'ISFJ cần những góp ý tích cực từ mọi người. Nếu thiếu những góp ý tích cực , động viên hay khi đối mặt với lời phê bình, ISFJ sẽ dễ bị nản lòng và có thể bị trầm cảm. Khi gặp chán nản hay căng thẳng trầm trọng, họ thường bi quan, tưởng tượng ra những điều tồi tệ sẽ xảy ra với họ. Họ có cảm xúc mạnh về sự không hoàn hảo, họ tin chắc rằng “Mọi thứ đã sai”, hay “Tôi không thể làm đúng được điều gì cả”.',
    },
    {
      'tinhcach':'ISFP',
      'tongquan1':'Có khoảng 8% dân số mang tính cách này. Tính cách ISFP này thường được xem như là tự phát nhất và không thể đoán trước của tất cả các loại hướng nội. Đặc tính nổi bậc của họ đó là sự thay đổi',
      'tongquan2':'ISFP yêu thích khám phá và theo đuổi cái mới, những ý tưởng và hoạt động mới. Họ rất giỏi trong việc cảm nhận những cơ hội như vậy, nhưng các đặc điểm tính cách ISFP cũng đẩy họ hướng tới trải nghiệm và đến với những ý tưởng mà không ai nghĩ đến trước đây. Các ISFP thường khá dễ dàng để thiết lập xu hướng mới và truyền cảm hứng cho những người khác - sở thích trải nghiệm của họ là không giống với bất kỳ loại tính cách khác.',
      'tongquan3':'Một đặc tính nổi trội khác của ISFP là yêu thích sự tự do - các ISFP rất độc lập và quyết liệt chống lại tất cả các hình thức kiểm soát. Những người có loại tính cách này được xem là "linh hồn tự do" tối cao, họ xem tất cả các quy định, hướng dẫn và truyền thống như giới hạn tự áp đặt làm cho cuộc sống buồn tẻ và nhàm chán. Các ISFP sống hoàn toàn trong hiện tại, không bám vào quá khứ hoặc chuẩn bị kế hoạch mở rộng trong tương lai - họ lấy những thứ khi chúng đến, họ sẽ thử nghiệm và điều chỉnh hành vi khi cần thiết. ISFP không có khái niệm vô trách nhiệm hay thiếu thận trọng.',
      'tongquan4':'Các ISFP thực sự làm tuyệt vời trong các lĩnh vực đòi hỏi phải có một cách tiếp cận độc lập về nghệ thuật. Họ cũng có xu hướng rất quyến rũ, chủ yếu là vì họ nhận thấy nó thực sự dễ dàng để nhận được những lời khen tốt nhất - sự nhạy cảm( F ) và kiểm soát tuyệt vời của tất cả năm giác quan ( S ) của ISFP đã giúp họ rất nhiều trong việc hòa hợp giữa thế giới vật chất và tinh thần. Do đó, các ISFP hiếm khi có khó khăn khi kết nối với những người khác, mặc dù thực tế rằng họ là người sống hướng nội ( I ). Ngay cả khi ISFP đang thực sự không thể lường trước hoặc thậm chí liều lĩnh, sự quyến rũ của họ dễ dàng tước "vũ khí" của những người xung quanh.',
      'tongquan5':'Rất đáng để nói rằng tính cách của ISFP rất tích cực theo đuổi mục tiêu, định hình những nguyên tắc và quy định nội bộ để hướng đến những mục tiêu đó. Điều này dù tốt hay xấu đều giúp ISFP thoát khỏi những kỳ vọng và hạn chế từ xã hội. Nếu như mục tiêu của ISFP tốt đẹp và cao cả, thì họ có thể rất vị tha, có thể từ thiện được và đầy cảm hứng đến mức kinh ngạc. Tuy nhiên, nếu như họ quyết đinh theo đuổi một mục tiêu vụ lợi, họ có thể trở thành vị kỷ, thậm chí quỷ quyệt, làm bất kì điều gì để đạt được mục đích. Những người có tính cách như thế này cần nhận thức được các khuynh hướng và câu hỏi cho động lực và lý tưởng của chính họ qua thời gian.',
    },
    {
      'tinhcach':'ISTJ',
      'tongquan1':'ISTJ là loại tính cách phổ biến nhất, có đến 13% dân số trên thế giới thuộc nhóm tính cách này. Phương châm sống của họ là “Chỉ có sự thật”, tính cách của ISTJ là rất tôn trọng sự thật, họ có xu hướng tiếp thu rất nhiều thông tin và nhớ rất lâu.ISTJ rất kỹ lưỡng, luôn luôn kiểm tra các sự kiện và không giả định bất cứ điều gì.',
      'tongquan2':'ISTJ được đánh giá là những người rất trung thành, đặc biệt là trong công việc. Tính chính xác, sự kiên nhẫn và khả năng tập trung cao khiến cho họ trở thành nhân viên lý tưởng trong nhiều ngành nghề. Vì vậy không ngạc nhiên, khi họ bị thu hút về các lĩnh vực: Dịch vụ công cộng, pháp luật, quân sự,…',
      'tongquan3':'ISTJ thường dành nhiều thời gian và công sức để thực hiện các công việc mà họ cho là quan trọng, đặc biệt là góp phần đạt được một mục tiêu cụ thể. Tuy nhiên, một cam kết  như vậy cũng có mặt tiêu cực – ISTJ sẽ không hề lay chuyển và chỉ dành rất ít thời gian để làm những việc mà họ không thấy có ý nghĩa, hoặc không thực tế, ví dụ như nghi thức xã hội. Tính cách của ISTJ là thích làm việc một mình, nhưng khi cần thiết họ vẫn có thể làm việc nhóm.',
      'tongquan4':'ISTJ là người luôn nhận trách nhiệm về hành động của mình và họ yêu thích quyền lực cũng bắt nguồn từ sự chịu trách nhiệm này. Họ thường biết rất nhiều nghề vì vậy họ có thể thành công trong nhiều lĩnh vực – ISTJ là người minh bạch, hợp lý, thông thái, họ mong muốn có cuộc sống ổn định và an toàn.',
      'tongquan5':'ISTJ dễ bực bội với những thiếu sót của người khác – Họ xem lời hứa là điều thiêng liêng và không thể hiểu “làm thế nào một người có ý thức lại không hoàn thành nghĩa vụ của mình”.',
    },
    {
      'tinhcach':'ISTP',
      'tongquan1':'Có khoảng 5% dân số mang tính cách này, ISTP sở hữu nhiều đặc điểm thú vị có thể dễ dàng ngăn chặn người ngoài cuộc thăm dò họ. Họ thường rất lý trí và suy nghĩ logic, nhưng cũng có thể làm ngạc nhiên mọi người bằng cách đột nhiên trở nên tự phát và nhiệt tình nhiều hơn. Trong khi hầu hết các loại tính cách khác thường dễ dàng nhận biết và vạch ra rõ ràng những tính cách đặc trưng, thì điều này chắc chắn là không thể với trường hợp của ISTP - ngay cả những người quen biết họ cũng có thể không có khả năng dự đoán phản ứng của họ với một điều gì đó.',
      'tongquan2':'Điều này xuất phát từ sự kết hợp thú vị của lý trí ( T ) và sự linh hoạt ( P ) trong đặc điểm tính cách ISTP. Những người mang tính cách này nghiêng về máy móc, có các kế hoạch và ý tưởng rất hợp lý, và họ có thể giữ bình tĩnh và lý trí trong một thời gian dài. Tuy nhiên, tính tự phát luôn ở bên trong họ - nó chỉ đơn giản là đang tạm ở "phía sau", tích lũy năng lượng và đang chờ thời điểm thích hợp để bùng phát nó cùng một lúc. Sự bùng phát đó thường làm mọi người xung quanh ngạc nhiên, đặc biệt là những người chưa từng thấy ISTP làm điều gì tương tự trước đây. Những người mang loại tính cách ISTP rất giỏi trong việc kiểm soát năng lượng và giữ chúng để làm những thứ quan trọng khác.',
      'tongquan3':'Các ISTP tỏa sáng trong các lĩnh vực có sự kết hợp giữa sáng tạo, tự do và thực tiễn. Họ có xu hướng trở thành các kỹ sư và người khắc phục sự cố(thám tử, cứu hỏa, cứu hộ,...) tuyệt vời, nhưng những thế mạnh này xuất phát từ kinh nghiệm thực tế của họ và tầm nhìn hơn là lý thuyết khoa học. ISTP rất nhanh chóng chán nản trong khi nghiên cứu, đặc biệt là nếu họ không thực sự nhìn thấy nó có thể áp dụng trong thực tế.',
      'tongquan4':'Sự công bằng và bình đẳng là hai quan điểm rất quan trọng với ISTP. Họ có thể "bẻ cong" hay phá vỡ các nguyên tắc hiện có để thực hiện quan điểm của minh. Do đó, bạn sẽ không bao giờ nhìn thấy một ISTP trong một môi trường mà nguyên tắc cá nhân của họ có thể bị xâm phạm. ISTP cũng rất trung thành với bạn bè của họ, nhưng họ có thể cần rất nhiều "thời gian một mình" để nạp năng lượng.',
      'tongquan5':'Nói chung, các ISTP có xu hướng rất lạc quan, hào phóng và tự tin trong khả năng của mình - miễn là họ không bị đặt vào một khuôn khổ, gánh nặng với các quy định và hướng dẫn, hoặc yêu cầu cam kết một cái gì đó họ chưa sẵn sàng. Những đặc điểm độc đáo và bí ẩn của loại tính cách này có thể không bao giờ ngừng làm cho những người gần gũi với họ ngạc nhiên, nhưng nó cũng có thể làm chính ISTP ngạc nhiên trong một khoảng khắc nào đó.',
    },
  ];

  int get getResult{
    int id;
    if (result =="ENFJ") {
      id = 0;
    } else if (result =="ENFP") {
      id = 1;
    } else if (result =="ENTJ") {
      id =2;
    } else if (result =="ENTP") {
      id = 3;
    } else if (result =="ESFJ") {
      id = 4;
    }else if (result =="ESFP") {
      id = 5;
    } else if (result =="ESTJ") {
      id = 6;
    } else if (result =="ESTP") {
      id = 7;
    } else if (result =="INFJ") {
      id = 8;
    } else if (result =="INFP") {
      id = 9;
    } else if (result =="INTJ") {
      id = 10;
    } else if (result =="INTP ") {
      id = 11;
    } else if (result =="ISFJ") {
      id = 12;
    }else if (result =="ISFP ") {
      id = 13;
    } else if (result =="ISTJ") {
      id = 14;
    }else {
      id = 15;
    }
    return id;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        padding:const EdgeInsets.all(8.0),
        child: ListView.builder(
          itemCount: 1,
          itemBuilder: (BuildContext context,_) {  
            return SingleChildScrollView(
              child: Column(
                children: [
                  TextDetail(tongquan[getResult]['tongquan1'] as String),
                  const SizedBoxDetail(),
                  TextDetail(tongquan[getResult]['tongquan2'] as String),
                  const SizedBoxDetail(), 
                  TextDetail(tongquan[getResult]['tongquan3'] as String),
                  const SizedBoxDetail(),       
                  TextDetail(tongquan[getResult]['tongquan4'] as String),
                  const SizedBoxDetail(), 
                  TextDetail(tongquan[getResult]['tongquan5'] as String),
                ],
              ));
          },
          
        ),
    );
  }
}